#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 128
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 52
#define ALIAS_COUNT 0
#define TOKEN_COUNT 28
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 6
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 4

enum {
  anon_sym_LBRACE_LBRACE = 1,
  anon_sym_RBRACE_RBRACE = 2,
  anon_sym_LBRACE_POUND = 3,
  anon_sym_POUND_RBRACE = 4,
  sym__single_quote = 5,
  sym__double_quote = 6,
  sym_string_content_sq = 7,
  sym_string_content_dq = 8,
  sym_integer = 9,
  sym_float = 10,
  anon_sym_LBRACK = 11,
  anon_sym_COMMA = 12,
  anon_sym_RBRACK = 13,
  anon_sym_LPAREN = 14,
  anon_sym_RPAREN = 15,
  anon_sym_LBRACE = 16,
  anon_sym_RBRACE = 17,
  anon_sym_COLON = 18,
  sym_true = 19,
  sym_false = 20,
  sym_none = 21,
  sym__identifier = 22,
  anon_sym_EQ = 23,
  sym_comment_content = 24,
  anon_sym_LBRACE_PERCENT = 25,
  aux_sym_jinja_expression_token1 = 26,
  sym__text = 27,
  sym_source_file = 28,
  sym_statement = 29,
  sym_expression = 30,
  sym_comment = 31,
  sym_text = 32,
  sym__expression = 33,
  sym__literal = 34,
  sym_string = 35,
  sym_single_quote = 36,
  sym_double_quote = 37,
  sym_list = 38,
  sym_tuple = 39,
  sym_dict = 40,
  sym_pair = 41,
  sym__bool = 42,
  sym_identifier = 43,
  sym_function = 44,
  sym_argument_list = 45,
  sym_kwarg = 46,
  sym_jinja_expression = 47,
  aux_sym_source_file_repeat1 = 48,
  aux_sym_list_repeat1 = 49,
  aux_sym_dict_repeat1 = 50,
  aux_sym_argument_list_repeat1 = 51,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACE_LBRACE] = "{{",
  [anon_sym_RBRACE_RBRACE] = "}}",
  [anon_sym_LBRACE_POUND] = "{#",
  [anon_sym_POUND_RBRACE] = "#}",
  [sym__single_quote] = "_single_quote",
  [sym__double_quote] = "_double_quote",
  [sym_string_content_sq] = "string_content_sq",
  [sym_string_content_dq] = "string_content_dq",
  [sym_integer] = "integer",
  [sym_float] = "float",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COLON] = ":",
  [sym_true] = "true",
  [sym_false] = "false",
  [sym_none] = "none",
  [sym__identifier] = "_identifier",
  [anon_sym_EQ] = "=",
  [sym_comment_content] = "comment_content",
  [anon_sym_LBRACE_PERCENT] = "{%",
  [aux_sym_jinja_expression_token1] = "jinja_expression_token1",
  [sym__text] = "_text",
  [sym_source_file] = "source_file",
  [sym_statement] = "statement",
  [sym_expression] = "expression",
  [sym_comment] = "comment",
  [sym_text] = "text",
  [sym__expression] = "_expression",
  [sym__literal] = "_literal",
  [sym_string] = "string",
  [sym_single_quote] = "single_quote",
  [sym_double_quote] = "double_quote",
  [sym_list] = "list",
  [sym_tuple] = "tuple",
  [sym_dict] = "dict",
  [sym_pair] = "pair",
  [sym__bool] = "_bool",
  [sym_identifier] = "identifier",
  [sym_function] = "function",
  [sym_argument_list] = "argument_list",
  [sym_kwarg] = "kwarg",
  [sym_jinja_expression] = "jinja_expression",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_list_repeat1] = "list_repeat1",
  [aux_sym_dict_repeat1] = "dict_repeat1",
  [aux_sym_argument_list_repeat1] = "argument_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACE_LBRACE] = anon_sym_LBRACE_LBRACE,
  [anon_sym_RBRACE_RBRACE] = anon_sym_RBRACE_RBRACE,
  [anon_sym_LBRACE_POUND] = anon_sym_LBRACE_POUND,
  [anon_sym_POUND_RBRACE] = anon_sym_POUND_RBRACE,
  [sym__single_quote] = sym__single_quote,
  [sym__double_quote] = sym__double_quote,
  [sym_string_content_sq] = sym_string_content_sq,
  [sym_string_content_dq] = sym_string_content_dq,
  [sym_integer] = sym_integer,
  [sym_float] = sym_float,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_true] = sym_true,
  [sym_false] = sym_false,
  [sym_none] = sym_none,
  [sym__identifier] = sym__identifier,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_comment_content] = sym_comment_content,
  [anon_sym_LBRACE_PERCENT] = anon_sym_LBRACE_PERCENT,
  [aux_sym_jinja_expression_token1] = aux_sym_jinja_expression_token1,
  [sym__text] = sym__text,
  [sym_source_file] = sym_source_file,
  [sym_statement] = sym_statement,
  [sym_expression] = sym_expression,
  [sym_comment] = sym_comment,
  [sym_text] = sym_text,
  [sym__expression] = sym__expression,
  [sym__literal] = sym__literal,
  [sym_string] = sym_string,
  [sym_single_quote] = sym_single_quote,
  [sym_double_quote] = sym_double_quote,
  [sym_list] = sym_list,
  [sym_tuple] = sym_tuple,
  [sym_dict] = sym_dict,
  [sym_pair] = sym_pair,
  [sym__bool] = sym__bool,
  [sym_identifier] = sym_identifier,
  [sym_function] = sym_function,
  [sym_argument_list] = sym_argument_list,
  [sym_kwarg] = sym_kwarg,
  [sym_jinja_expression] = sym_jinja_expression,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_list_repeat1] = aux_sym_list_repeat1,
  [aux_sym_dict_repeat1] = aux_sym_dict_repeat1,
  [aux_sym_argument_list_repeat1] = aux_sym_argument_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym__single_quote] = {
    .visible = false,
    .named = true,
  },
  [sym__double_quote] = {
    .visible = false,
    .named = true,
  },
  [sym_string_content_sq] = {
    .visible = true,
    .named = true,
  },
  [sym_string_content_dq] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_true] = {
    .visible = true,
    .named = true,
  },
  [sym_false] = {
    .visible = true,
    .named = true,
  },
  [sym_none] = {
    .visible = true,
    .named = true,
  },
  [sym__identifier] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_comment_content] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_jinja_expression_token1] = {
    .visible = false,
    .named = false,
  },
  [sym__text] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym__literal] = {
    .visible = false,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_single_quote] = {
    .visible = true,
    .named = true,
  },
  [sym_double_quote] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym_tuple] = {
    .visible = true,
    .named = true,
  },
  [sym_dict] = {
    .visible = true,
    .named = true,
  },
  [sym_pair] = {
    .visible = true,
    .named = true,
  },
  [sym__bool] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_function] = {
    .visible = true,
    .named = true,
  },
  [sym_argument_list] = {
    .visible = true,
    .named = true,
  },
  [sym_kwarg] = {
    .visible = true,
    .named = true,
  },
  [sym_jinja_expression] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_dict_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_argument_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_argument_list = 1,
  field_key = 2,
  field_name = 3,
  field_quote_type = 4,
  field_string_content = 5,
  field_value = 6,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_argument_list] = "argument_list",
  [field_key] = "key",
  [field_name] = "name",
  [field_quote_type] = "quote_type",
  [field_string_content] = "string_content",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 2},
  [3] = {.index = 4, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_argument_list, 1},
    {field_name, 0},
  [2] =
    {field_quote_type, 0},
    {field_string_content, 1},
  [4] =
    {field_key, 0},
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 4,
  [6] = 6,
  [7] = 7,
  [8] = 7,
  [9] = 6,
  [10] = 10,
  [11] = 10,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 12,
  [18] = 15,
  [19] = 16,
  [20] = 14,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 27,
  [29] = 29,
  [30] = 29,
  [31] = 31,
  [32] = 31,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 34,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 62,
  [64] = 64,
  [65] = 65,
  [66] = 64,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 69,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 67,
  [75] = 71,
  [76] = 76,
  [77] = 65,
  [78] = 78,
  [79] = 72,
  [80] = 33,
  [81] = 73,
  [82] = 49,
  [83] = 60,
  [84] = 54,
  [85] = 55,
  [86] = 52,
  [87] = 48,
  [88] = 45,
  [89] = 40,
  [90] = 50,
  [91] = 53,
  [92] = 57,
  [93] = 47,
  [94] = 61,
  [95] = 51,
  [96] = 43,
  [97] = 44,
  [98] = 46,
  [99] = 59,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 105,
  [109] = 104,
  [110] = 110,
  [111] = 106,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 107,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 110,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 118,
  [125] = 125,
  [126] = 116,
  [127] = 114,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(15);
      if (lookahead == '"') ADVANCE(21);
      if (lookahead == '#') ADVANCE(6);
      if (lookahead == '\'') ADVANCE(20);
      if (lookahead == '(') ADVANCE(39);
      if (lookahead == ')') ADVANCE(40);
      if (lookahead == ',') ADVANCE(37);
      if (lookahead == '.') ADVANCE(10);
      if (lookahead == ':') ADVANCE(44);
      if (lookahead == '=') ADVANCE(59);
      if (lookahead == '[') ADVANCE(36);
      if (lookahead == ']') ADVANCE(38);
      if (lookahead == '{') ADVANCE(42);
      if (lookahead == '}') ADVANCE(43);
      if (('+' <= lookahead && lookahead <= '-')) ADVANCE(5);
      if (lookahead == 'F' ||
          lookahead == 'f') ADVANCE(48);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(54);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(55);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(21);
      if (lookahead == '\'') ADVANCE(20);
      if (lookahead == '(') ADVANCE(39);
      if (lookahead == ')') ADVANCE(40);
      if (lookahead == ',') ADVANCE(37);
      if (lookahead == '.') ADVANCE(10);
      if (lookahead == ':') ADVANCE(44);
      if (lookahead == '=') ADVANCE(59);
      if (lookahead == '[') ADVANCE(36);
      if (lookahead == ']') ADVANCE(38);
      if (lookahead == '{') ADVANCE(41);
      if (lookahead == '}') ADVANCE(7);
      if (('+' <= lookahead && lookahead <= '-')) ADVANCE(5);
      if (lookahead == 'F' ||
          lookahead == 'f') ADVANCE(48);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(54);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(55);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 2:
      if (lookahead == '#') ADVANCE(18);
      if (lookahead == '%') ADVANCE(62);
      if (lookahead == '{') ADVANCE(16);
      if (lookahead != 0) ADVANCE(65);
      END_STATE();
    case 3:
      if (lookahead == '%') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(3);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 4:
      if (lookahead == '%') ADVANCE(8);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '.') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      END_STATE();
    case 6:
      if (lookahead == '}') ADVANCE(19);
      END_STATE();
    case 7:
      if (lookahead == '}') ADVANCE(17);
      END_STATE();
    case 8:
      if (lookahead == '}') ADVANCE(63);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 9:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      END_STATE();
    case 10:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 11:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      END_STATE();
    case 12:
      if (lookahead != 0 &&
          lookahead != '#' &&
          lookahead != '%' &&
          lookahead != '{') ADVANCE(65);
      END_STATE();
    case 13:
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(61);
      END_STATE();
    case 14:
      if (eof) ADVANCE(15);
      if (lookahead == '{') ADVANCE(2);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(64);
      if (lookahead != 0) ADVANCE(65);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LBRACE_POUND);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_POUND_RBRACE);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym__single_quote);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym__double_quote);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_string_content_sq);
      if (lookahead == '\\') ADVANCE(24);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(23);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_string_content_sq);
      if (lookahead == '\\') ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_string_content_sq);
      if (lookahead != 0 &&
          lookahead != '\\') ADVANCE(23);
      if (lookahead == '\\') ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_string_content_dq);
      if (lookahead == '\\') ADVANCE(27);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(26);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_string_content_dq);
      if (lookahead == '\\') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_string_content_dq);
      if (lookahead != 0 &&
          lookahead != '\\') ADVANCE(26);
      if (lookahead == '\\') ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '.') ADVANCE(34);
      if (lookahead == '_') ADVANCE(30);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '.') ADVANCE(34);
      if (lookahead == '_') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '.') ADVANCE(34);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '.') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_float);
      if (lookahead == '_') ADVANCE(34);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_float);
      if (lookahead == '_') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_float);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_float);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead == '#') ADVANCE(18);
      if (lookahead == '%') ADVANCE(62);
      if (lookahead == '{') ADVANCE(16);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_true);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_false);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_none);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead == 'a') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead == 'e') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead == 'e') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead == 'e') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead == 'l') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead == 'n') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead == 'o') ADVANCE(53);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead == 'r') ADVANCE(57);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead == 's') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead == 'u') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym__identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_comment_content);
      if (lookahead == '#') ADVANCE(13);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(60);
      if (lookahead != 0) ADVANCE(61);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_comment_content);
      if (lookahead == '#') ADVANCE(13);
      if (lookahead != 0) ADVANCE(61);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_LBRACE_PERCENT);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(aux_sym_jinja_expression_token1);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym__text);
      if (lookahead == '{') ADVANCE(2);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(64);
      if (lookahead != 0) ADVANCE(65);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym__text);
      if (lookahead == '{') ADVANCE(12);
      if (lookahead != 0) ADVANCE(65);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 14},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 14},
  [26] = {.lex_state = 14},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 14},
  [37] = {.lex_state = 14},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 14},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 14},
  [42] = {.lex_state = 14},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 1},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 1},
  [60] = {.lex_state = 1},
  [61] = {.lex_state = 1},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 60},
  [114] = {.lex_state = 25},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 22},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 1},
  [121] = {.lex_state = 25},
  [122] = {.lex_state = 22},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 3},
  [126] = {.lex_state = 22},
  [127] = {.lex_state = 25},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(1),
    [anon_sym_LBRACE_POUND] = ACTIONS(1),
    [anon_sym_POUND_RBRACE] = ACTIONS(1),
    [sym__single_quote] = ACTIONS(1),
    [sym__double_quote] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [sym_float] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_true] = ACTIONS(1),
    [sym_false] = ACTIONS(1),
    [sym_none] = ACTIONS(1),
    [sym__identifier] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LBRACE_PERCENT] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(123),
    [sym_statement] = STATE(26),
    [sym_expression] = STATE(26),
    [sym_comment] = STATE(26),
    [sym_text] = STATE(26),
    [sym_jinja_expression] = STATE(37),
    [aux_sym_source_file_repeat1] = STATE(26),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(5),
    [anon_sym_LBRACE_POUND] = ACTIONS(7),
    [anon_sym_LBRACE_PERCENT] = ACTIONS(9),
    [sym__text] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 14,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(19), 1,
      sym_float,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_COMMA,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      anon_sym_RPAREN,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym__identifier,
    STATE(38), 1,
      sym_identifier,
    STATE(114), 1,
      sym_double_quote,
    STATE(116), 1,
      sym_single_quote,
    ACTIONS(17), 4,
      sym_integer,
      sym_true,
      sym_false,
      sym_none,
    STATE(70), 9,
      sym__expression,
      sym__literal,
      sym_string,
      sym_list,
      sym_tuple,
      sym_dict,
      sym__bool,
      sym_function,
      sym_kwarg,
  [54] = 14,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym__identifier,
    ACTIONS(35), 1,
      sym_float,
    ACTIONS(37), 1,
      anon_sym_COMMA,
    ACTIONS(39), 1,
      anon_sym_RPAREN,
    STATE(38), 1,
      sym_identifier,
    STATE(114), 1,
      sym_double_quote,
    STATE(116), 1,
      sym_single_quote,
    ACTIONS(33), 4,
      sym_integer,
      sym_true,
      sym_false,
      sym_none,
    STATE(69), 9,
      sym__expression,
      sym__literal,
      sym_string,
      sym_list,
      sym_tuple,
      sym_dict,
      sym__bool,
      sym_function,
      sym_kwarg,
  [108] = 14,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym__identifier,
    ACTIONS(43), 1,
      sym_float,
    ACTIONS(45), 1,
      anon_sym_COMMA,
    ACTIONS(47), 1,
      anon_sym_RPAREN,
    STATE(34), 1,
      sym_identifier,
    STATE(114), 1,
      sym_double_quote,
    STATE(116), 1,
      sym_single_quote,
    ACTIONS(41), 4,
      sym_integer,
      sym_true,
      sym_false,
      sym_none,
    STATE(77), 8,
      sym__expression,
      sym__literal,
      sym_string,
      sym_list,
      sym_tuple,
      sym_dict,
      sym__bool,
      sym_function,
  [161] = 14,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym__identifier,
    ACTIONS(51), 1,
      sym_float,
    ACTIONS(53), 1,
      anon_sym_COMMA,
    ACTIONS(55), 1,
      anon_sym_RPAREN,
    STATE(34), 1,
      sym_identifier,
    STATE(114), 1,
      sym_double_quote,
    STATE(116), 1,
      sym_single_quote,
    ACTIONS(49), 4,
      sym_integer,
      sym_true,
      sym_false,
      sym_none,
    STATE(65), 8,
      sym__expression,
      sym__literal,
      sym_string,
      sym_list,
      sym_tuple,
      sym_dict,
      sym__bool,
      sym_function,
  [214] = 13,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym__identifier,
    ACTIONS(59), 1,
      sym_float,
    ACTIONS(61), 1,
      anon_sym_RPAREN,
    STATE(38), 1,
      sym_identifier,
    STATE(114), 1,
      sym_double_quote,
    STATE(116), 1,
      sym_single_quote,
    ACTIONS(57), 4,
      sym_integer,
      sym_true,
      sym_false,
      sym_none,
    STATE(102), 9,
      sym__expression,
      sym__literal,
      sym_string,
      sym_list,
      sym_tuple,
      sym_dict,
      sym__bool,
      sym_function,
      sym_kwarg,
  [265] = 13,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym__identifier,
    ACTIONS(59), 1,
      sym_float,
    ACTIONS(63), 1,
      anon_sym_RPAREN,
    STATE(38), 1,
      sym_identifier,
    STATE(114), 1,
      sym_double_quote,
    STATE(116), 1,
      sym_single_quote,
    ACTIONS(57), 4,
      sym_integer,
      sym_true,
      sym_false,
      sym_none,
    STATE(102), 9,
      sym__expression,
      sym__literal,
      sym_string,
      sym_list,
      sym_tuple,
      sym_dict,
      sym__bool,
      sym_function,
      sym_kwarg,
  [316] = 13,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym__identifier,
    ACTIONS(59), 1,
      sym_float,
    ACTIONS(65), 1,
      anon_sym_RPAREN,
    STATE(38), 1,
      sym_identifier,
    STATE(114), 1,
      sym_double_quote,
    STATE(116), 1,
      sym_single_quote,
    ACTIONS(57), 4,
      sym_integer,
      sym_true,
      sym_false,
      sym_none,
    STATE(102), 9,
      sym__expression,
      sym__literal,
      sym_string,
      sym_list,
      sym_tuple,
      sym_dict,
      sym__bool,
      sym_function,
      sym_kwarg,
  [367] = 13,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym__identifier,
    ACTIONS(59), 1,
      sym_float,
    ACTIONS(67), 1,
      anon_sym_RPAREN,
    STATE(38), 1,
      sym_identifier,
    STATE(114), 1,
      sym_double_quote,
    STATE(116), 1,
      sym_single_quote,
    ACTIONS(57), 4,
      sym_integer,
      sym_true,
      sym_false,
      sym_none,
    STATE(102), 9,
      sym__expression,
      sym__literal,
      sym_string,
      sym_list,
      sym_tuple,
      sym_dict,
      sym__bool,
      sym_function,
      sym_kwarg,
  [418] = 14,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym__identifier,
    ACTIONS(71), 1,
      sym_float,
    ACTIONS(73), 1,
      anon_sym_COMMA,
    ACTIONS(75), 1,
      anon_sym_RBRACK,
    STATE(34), 1,
      sym_identifier,
    STATE(114), 1,
      sym_double_quote,
    STATE(116), 1,
      sym_single_quote,
    ACTIONS(69), 4,
      sym_integer,
      sym_true,
      sym_false,
      sym_none,
    STATE(67), 8,
      sym__expression,
      sym__literal,
      sym_string,
      sym_list,
      sym_tuple,
      sym_dict,
      sym__bool,
      sym_function,
  [471] = 14,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym__identifier,
    ACTIONS(79), 1,
      sym_float,
    ACTIONS(81), 1,
      anon_sym_COMMA,
    ACTIONS(83), 1,
      anon_sym_RBRACK,
    STATE(34), 1,
      sym_identifier,
    STATE(114), 1,
      sym_double_quote,
    STATE(116), 1,
      sym_single_quote,
    ACTIONS(77), 4,
      sym_integer,
      sym_true,
      sym_false,
      sym_none,
    STATE(74), 8,
      sym__expression,
      sym__literal,
      sym_string,
      sym_list,
      sym_tuple,
      sym_dict,
      sym__bool,
      sym_function,
  [524] = 13,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym__identifier,
    ACTIONS(87), 1,
      sym_float,
    ACTIONS(89), 1,
      anon_sym_RBRACK,
    STATE(34), 1,
      sym_identifier,
    STATE(114), 1,
      sym_double_quote,
    STATE(116), 1,
      sym_single_quote,
    ACTIONS(85), 4,
      sym_integer,
      sym_true,
      sym_false,
      sym_none,
    STATE(68), 8,
      sym__expression,
      sym__literal,
      sym_string,
      sym_list,
      sym_tuple,
      sym_dict,
      sym__bool,
      sym_function,
  [574] = 12,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym__identifier,
    ACTIONS(59), 1,
      sym_float,
    STATE(38), 1,
      sym_identifier,
    STATE(114), 1,
      sym_double_quote,
    STATE(116), 1,
      sym_single_quote,
    ACTIONS(57), 4,
      sym_integer,
      sym_true,
      sym_false,
      sym_none,
    STATE(102), 9,
      sym__expression,
      sym__literal,
      sym_string,
      sym_list,
      sym_tuple,
      sym_dict,
      sym__bool,
      sym_function,
      sym_kwarg,
  [622] = 13,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym__identifier,
    ACTIONS(87), 1,
      sym_float,
    ACTIONS(91), 1,
      anon_sym_RPAREN,
    STATE(34), 1,
      sym_identifier,
    STATE(114), 1,
      sym_double_quote,
    STATE(116), 1,
      sym_single_quote,
    ACTIONS(85), 4,
      sym_integer,
      sym_true,
      sym_false,
      sym_none,
    STATE(68), 8,
      sym__expression,
      sym__literal,
      sym_string,
      sym_list,
      sym_tuple,
      sym_dict,
      sym__bool,
      sym_function,
  [672] = 13,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym__identifier,
    ACTIONS(87), 1,
      sym_float,
    ACTIONS(93), 1,
      anon_sym_RPAREN,
    STATE(34), 1,
      sym_identifier,
    STATE(114), 1,
      sym_double_quote,
    STATE(116), 1,
      sym_single_quote,
    ACTIONS(85), 4,
      sym_integer,
      sym_true,
      sym_false,
      sym_none,
    STATE(68), 8,
      sym__expression,
      sym__literal,
      sym_string,
      sym_list,
      sym_tuple,
      sym_dict,
      sym__bool,
      sym_function,
  [722] = 13,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym__identifier,
    ACTIONS(87), 1,
      sym_float,
    ACTIONS(95), 1,
      anon_sym_RBRACK,
    STATE(34), 1,
      sym_identifier,
    STATE(114), 1,
      sym_double_quote,
    STATE(116), 1,
      sym_single_quote,
    ACTIONS(85), 4,
      sym_integer,
      sym_true,
      sym_false,
      sym_none,
    STATE(68), 8,
      sym__expression,
      sym__literal,
      sym_string,
      sym_list,
      sym_tuple,
      sym_dict,
      sym__bool,
      sym_function,
  [772] = 13,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym__identifier,
    ACTIONS(87), 1,
      sym_float,
    ACTIONS(97), 1,
      anon_sym_RBRACK,
    STATE(34), 1,
      sym_identifier,
    STATE(114), 1,
      sym_double_quote,
    STATE(116), 1,
      sym_single_quote,
    ACTIONS(85), 4,
      sym_integer,
      sym_true,
      sym_false,
      sym_none,
    STATE(68), 8,
      sym__expression,
      sym__literal,
      sym_string,
      sym_list,
      sym_tuple,
      sym_dict,
      sym__bool,
      sym_function,
  [822] = 13,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym__identifier,
    ACTIONS(87), 1,
      sym_float,
    ACTIONS(99), 1,
      anon_sym_RPAREN,
    STATE(34), 1,
      sym_identifier,
    STATE(114), 1,
      sym_double_quote,
    STATE(116), 1,
      sym_single_quote,
    ACTIONS(85), 4,
      sym_integer,
      sym_true,
      sym_false,
      sym_none,
    STATE(68), 8,
      sym__expression,
      sym__literal,
      sym_string,
      sym_list,
      sym_tuple,
      sym_dict,
      sym__bool,
      sym_function,
  [872] = 13,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym__identifier,
    ACTIONS(87), 1,
      sym_float,
    ACTIONS(101), 1,
      anon_sym_RBRACK,
    STATE(34), 1,
      sym_identifier,
    STATE(114), 1,
      sym_double_quote,
    STATE(116), 1,
      sym_single_quote,
    ACTIONS(85), 4,
      sym_integer,
      sym_true,
      sym_false,
      sym_none,
    STATE(68), 8,
      sym__expression,
      sym__literal,
      sym_string,
      sym_list,
      sym_tuple,
      sym_dict,
      sym__bool,
      sym_function,
  [922] = 13,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym__identifier,
    ACTIONS(87), 1,
      sym_float,
    ACTIONS(103), 1,
      anon_sym_RPAREN,
    STATE(34), 1,
      sym_identifier,
    STATE(114), 1,
      sym_double_quote,
    STATE(116), 1,
      sym_single_quote,
    ACTIONS(85), 4,
      sym_integer,
      sym_true,
      sym_false,
      sym_none,
    STATE(68), 8,
      sym__expression,
      sym__literal,
      sym_string,
      sym_list,
      sym_tuple,
      sym_dict,
      sym__bool,
      sym_function,
  [972] = 12,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym__identifier,
    ACTIONS(107), 1,
      sym_float,
    STATE(34), 1,
      sym_identifier,
    STATE(114), 1,
      sym_double_quote,
    STATE(116), 1,
      sym_single_quote,
    ACTIONS(105), 4,
      sym_integer,
      sym_true,
      sym_false,
      sym_none,
    STATE(101), 8,
      sym__expression,
      sym__literal,
      sym_string,
      sym_list,
      sym_tuple,
      sym_dict,
      sym__bool,
      sym_function,
  [1019] = 12,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym__identifier,
    ACTIONS(87), 1,
      sym_float,
    STATE(34), 1,
      sym_identifier,
    STATE(114), 1,
      sym_double_quote,
    STATE(116), 1,
      sym_single_quote,
    ACTIONS(85), 4,
      sym_integer,
      sym_true,
      sym_false,
      sym_none,
    STATE(68), 8,
      sym__expression,
      sym__literal,
      sym_string,
      sym_list,
      sym_tuple,
      sym_dict,
      sym__bool,
      sym_function,
  [1066] = 12,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(111), 1,
      sym_float,
    ACTIONS(113), 1,
      anon_sym_LBRACK,
    ACTIONS(115), 1,
      anon_sym_LPAREN,
    ACTIONS(117), 1,
      anon_sym_LBRACE,
    ACTIONS(119), 1,
      sym__identifier,
    STATE(58), 1,
      sym_identifier,
    STATE(126), 1,
      sym_single_quote,
    STATE(127), 1,
      sym_double_quote,
    ACTIONS(109), 4,
      sym_integer,
      sym_true,
      sym_false,
      sym_none,
    STATE(103), 8,
      sym__expression,
      sym__literal,
      sym_string,
      sym_list,
      sym_tuple,
      sym_dict,
      sym__bool,
      sym_function,
  [1113] = 12,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym__identifier,
    ACTIONS(123), 1,
      sym_float,
    STATE(34), 1,
      sym_identifier,
    STATE(114), 1,
      sym_double_quote,
    STATE(116), 1,
      sym_single_quote,
    ACTIONS(121), 4,
      sym_integer,
      sym_true,
      sym_false,
      sym_none,
    STATE(120), 8,
      sym__expression,
      sym__literal,
      sym_string,
      sym_list,
      sym_tuple,
      sym_dict,
      sym__bool,
      sym_function,
  [1160] = 7,
    ACTIONS(125), 1,
      ts_builtin_sym_end,
    ACTIONS(127), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(130), 1,
      anon_sym_LBRACE_POUND,
    ACTIONS(133), 1,
      anon_sym_LBRACE_PERCENT,
    ACTIONS(136), 1,
      sym__text,
    STATE(37), 1,
      sym_jinja_expression,
    STATE(25), 5,
      sym_statement,
      sym_expression,
      sym_comment,
      sym_text,
      aux_sym_source_file_repeat1,
  [1186] = 7,
    ACTIONS(5), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(7), 1,
      anon_sym_LBRACE_POUND,
    ACTIONS(9), 1,
      anon_sym_LBRACE_PERCENT,
    ACTIONS(11), 1,
      sym__text,
    ACTIONS(139), 1,
      ts_builtin_sym_end,
    STATE(37), 1,
      sym_jinja_expression,
    STATE(25), 5,
      sym_statement,
      sym_expression,
      sym_comment,
      sym_text,
      aux_sym_source_file_repeat1,
  [1212] = 8,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(141), 1,
      anon_sym_COMMA,
    ACTIONS(143), 1,
      anon_sym_RBRACE,
    STATE(63), 1,
      sym_pair,
    STATE(114), 1,
      sym_double_quote,
    STATE(116), 1,
      sym_single_quote,
    STATE(117), 1,
      sym_string,
  [1237] = 8,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(145), 1,
      anon_sym_COMMA,
    ACTIONS(147), 1,
      anon_sym_RBRACE,
    STATE(62), 1,
      sym_pair,
    STATE(114), 1,
      sym_double_quote,
    STATE(116), 1,
      sym_single_quote,
    STATE(117), 1,
      sym_string,
  [1262] = 7,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(149), 1,
      anon_sym_RBRACE,
    STATE(100), 1,
      sym_pair,
    STATE(114), 1,
      sym_double_quote,
    STATE(116), 1,
      sym_single_quote,
    STATE(117), 1,
      sym_string,
  [1284] = 7,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(151), 1,
      anon_sym_RBRACE,
    STATE(100), 1,
      sym_pair,
    STATE(114), 1,
      sym_double_quote,
    STATE(116), 1,
      sym_single_quote,
    STATE(117), 1,
      sym_string,
  [1306] = 7,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(153), 1,
      anon_sym_RBRACE,
    STATE(100), 1,
      sym_pair,
    STATE(114), 1,
      sym_double_quote,
    STATE(116), 1,
      sym_single_quote,
    STATE(117), 1,
      sym_string,
  [1328] = 7,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(155), 1,
      anon_sym_RBRACE,
    STATE(100), 1,
      sym_pair,
    STATE(114), 1,
      sym_double_quote,
    STATE(116), 1,
      sym_single_quote,
    STATE(117), 1,
      sym_string,
  [1350] = 1,
    ACTIONS(157), 6,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_EQ,
  [1359] = 3,
    ACTIONS(161), 1,
      anon_sym_LPAREN,
    STATE(55), 1,
      sym_argument_list,
    ACTIONS(159), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1372] = 6,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    STATE(100), 1,
      sym_pair,
    STATE(114), 1,
      sym_double_quote,
    STATE(116), 1,
      sym_single_quote,
    STATE(117), 1,
      sym_string,
  [1391] = 2,
    ACTIONS(163), 2,
      ts_builtin_sym_end,
      sym__text,
    ACTIONS(165), 3,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_PERCENT,
  [1401] = 2,
    ACTIONS(167), 2,
      ts_builtin_sym_end,
      sym__text,
    ACTIONS(169), 3,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_PERCENT,
  [1411] = 4,
    ACTIONS(161), 1,
      anon_sym_LPAREN,
    ACTIONS(171), 1,
      anon_sym_EQ,
    STATE(55), 1,
      sym_argument_list,
    ACTIONS(159), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1425] = 2,
    ACTIONS(173), 2,
      ts_builtin_sym_end,
      sym__text,
    ACTIONS(175), 3,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_PERCENT,
  [1435] = 1,
    ACTIONS(177), 5,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_COLON,
  [1443] = 2,
    ACTIONS(179), 2,
      ts_builtin_sym_end,
      sym__text,
    ACTIONS(181), 3,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_PERCENT,
  [1453] = 2,
    ACTIONS(183), 2,
      ts_builtin_sym_end,
      sym__text,
    ACTIONS(185), 3,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_PERCENT,
  [1463] = 1,
    ACTIONS(187), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1470] = 1,
    ACTIONS(189), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1477] = 1,
    ACTIONS(191), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1484] = 1,
    ACTIONS(193), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1491] = 1,
    ACTIONS(195), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1498] = 1,
    ACTIONS(197), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1505] = 1,
    ACTIONS(199), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1512] = 1,
    ACTIONS(201), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1519] = 1,
    ACTIONS(203), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1526] = 1,
    ACTIONS(205), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1533] = 1,
    ACTIONS(207), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1540] = 1,
    ACTIONS(209), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1547] = 1,
    ACTIONS(211), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1554] = 3,
    ACTIONS(213), 1,
      anon_sym_COMMA,
    STATE(56), 1,
      aux_sym_list_repeat1,
    ACTIONS(216), 2,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1565] = 1,
    ACTIONS(218), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1572] = 3,
    ACTIONS(220), 1,
      anon_sym_LPAREN,
    STATE(85), 1,
      sym_argument_list,
    ACTIONS(159), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1583] = 1,
    ACTIONS(222), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1590] = 1,
    ACTIONS(224), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1597] = 1,
    ACTIONS(226), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1604] = 3,
    ACTIONS(228), 1,
      anon_sym_COMMA,
    ACTIONS(230), 1,
      anon_sym_RBRACE,
    STATE(71), 1,
      aux_sym_dict_repeat1,
  [1614] = 3,
    ACTIONS(232), 1,
      anon_sym_COMMA,
    ACTIONS(234), 1,
      anon_sym_RBRACE,
    STATE(75), 1,
      aux_sym_dict_repeat1,
  [1624] = 3,
    ACTIONS(63), 1,
      anon_sym_RPAREN,
    ACTIONS(236), 1,
      anon_sym_COMMA,
    STATE(76), 1,
      aux_sym_argument_list_repeat1,
  [1634] = 3,
    ACTIONS(238), 1,
      anon_sym_COMMA,
    ACTIONS(240), 1,
      anon_sym_RPAREN,
    STATE(79), 1,
      aux_sym_list_repeat1,
  [1644] = 3,
    ACTIONS(65), 1,
      anon_sym_RPAREN,
    ACTIONS(242), 1,
      anon_sym_COMMA,
    STATE(76), 1,
      aux_sym_argument_list_repeat1,
  [1654] = 3,
    ACTIONS(244), 1,
      anon_sym_COMMA,
    ACTIONS(246), 1,
      anon_sym_RBRACK,
    STATE(81), 1,
      aux_sym_list_repeat1,
  [1664] = 1,
    ACTIONS(216), 3,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1670] = 3,
    ACTIONS(248), 1,
      anon_sym_COMMA,
    ACTIONS(250), 1,
      anon_sym_RPAREN,
    STATE(66), 1,
      aux_sym_argument_list_repeat1,
  [1680] = 3,
    ACTIONS(252), 1,
      anon_sym_COMMA,
    ACTIONS(254), 1,
      anon_sym_RPAREN,
    STATE(64), 1,
      aux_sym_argument_list_repeat1,
  [1690] = 3,
    ACTIONS(149), 1,
      anon_sym_RBRACE,
    ACTIONS(256), 1,
      anon_sym_COMMA,
    STATE(78), 1,
      aux_sym_dict_repeat1,
  [1700] = 3,
    ACTIONS(99), 1,
      anon_sym_RPAREN,
    ACTIONS(258), 1,
      anon_sym_COMMA,
    STATE(56), 1,
      aux_sym_list_repeat1,
  [1710] = 3,
    ACTIONS(101), 1,
      anon_sym_RBRACK,
    ACTIONS(260), 1,
      anon_sym_COMMA,
    STATE(56), 1,
      aux_sym_list_repeat1,
  [1720] = 3,
    ACTIONS(262), 1,
      anon_sym_COMMA,
    ACTIONS(264), 1,
      anon_sym_RBRACK,
    STATE(73), 1,
      aux_sym_list_repeat1,
  [1730] = 3,
    ACTIONS(151), 1,
      anon_sym_RBRACE,
    ACTIONS(266), 1,
      anon_sym_COMMA,
    STATE(78), 1,
      aux_sym_dict_repeat1,
  [1740] = 3,
    ACTIONS(268), 1,
      anon_sym_COMMA,
    ACTIONS(271), 1,
      anon_sym_RPAREN,
    STATE(76), 1,
      aux_sym_argument_list_repeat1,
  [1750] = 3,
    ACTIONS(273), 1,
      anon_sym_COMMA,
    ACTIONS(275), 1,
      anon_sym_RPAREN,
    STATE(72), 1,
      aux_sym_list_repeat1,
  [1760] = 3,
    ACTIONS(277), 1,
      anon_sym_COMMA,
    ACTIONS(280), 1,
      anon_sym_RBRACE,
    STATE(78), 1,
      aux_sym_dict_repeat1,
  [1770] = 3,
    ACTIONS(93), 1,
      anon_sym_RPAREN,
    ACTIONS(282), 1,
      anon_sym_COMMA,
    STATE(56), 1,
      aux_sym_list_repeat1,
  [1780] = 1,
    ACTIONS(157), 3,
      anon_sym_COMMA,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
  [1786] = 3,
    ACTIONS(95), 1,
      anon_sym_RBRACK,
    ACTIONS(284), 1,
      anon_sym_COMMA,
    STATE(56), 1,
      aux_sym_list_repeat1,
  [1796] = 1,
    ACTIONS(199), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1801] = 1,
    ACTIONS(224), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1806] = 1,
    ACTIONS(209), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1811] = 1,
    ACTIONS(211), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1816] = 1,
    ACTIONS(205), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1821] = 1,
    ACTIONS(197), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1826] = 1,
    ACTIONS(191), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1831] = 1,
    ACTIONS(177), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1836] = 1,
    ACTIONS(201), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1841] = 1,
    ACTIONS(207), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1846] = 1,
    ACTIONS(218), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1851] = 1,
    ACTIONS(195), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1856] = 1,
    ACTIONS(226), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1861] = 1,
    ACTIONS(203), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1866] = 1,
    ACTIONS(187), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1871] = 1,
    ACTIONS(189), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1876] = 1,
    ACTIONS(193), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1881] = 1,
    ACTIONS(222), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1886] = 1,
    ACTIONS(280), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1891] = 1,
    ACTIONS(286), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1896] = 1,
    ACTIONS(271), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1901] = 1,
    ACTIONS(288), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1906] = 1,
    ACTIONS(290), 1,
      sym__single_quote,
  [1910] = 1,
    ACTIONS(240), 1,
      anon_sym_RPAREN,
  [1914] = 1,
    ACTIONS(246), 1,
      anon_sym_RBRACK,
  [1918] = 1,
    ACTIONS(234), 1,
      anon_sym_RBRACE,
  [1922] = 1,
    ACTIONS(275), 1,
      anon_sym_RPAREN,
  [1926] = 1,
    ACTIONS(292), 1,
      sym__single_quote,
  [1930] = 1,
    ACTIONS(292), 1,
      sym__double_quote,
  [1934] = 1,
    ACTIONS(264), 1,
      anon_sym_RBRACK,
  [1938] = 1,
    ACTIONS(294), 1,
      anon_sym_POUND_RBRACE,
  [1942] = 1,
    ACTIONS(296), 1,
      sym_comment_content,
  [1946] = 1,
    ACTIONS(298), 1,
      sym_string_content_dq,
  [1950] = 1,
    ACTIONS(230), 1,
      anon_sym_RBRACE,
  [1954] = 1,
    ACTIONS(300), 1,
      sym_string_content_sq,
  [1958] = 1,
    ACTIONS(302), 1,
      anon_sym_COLON,
  [1962] = 1,
    ACTIONS(254), 1,
      anon_sym_RPAREN,
  [1966] = 1,
    ACTIONS(290), 1,
      sym__double_quote,
  [1970] = 1,
    ACTIONS(304), 1,
      anon_sym_RBRACE_RBRACE,
  [1974] = 1,
    ACTIONS(306), 1,
      sym_string_content_dq,
  [1978] = 1,
    ACTIONS(308), 1,
      sym_string_content_sq,
  [1982] = 1,
    ACTIONS(310), 1,
      ts_builtin_sym_end,
  [1986] = 1,
    ACTIONS(250), 1,
      anon_sym_RPAREN,
  [1990] = 1,
    ACTIONS(312), 1,
      aux_sym_jinja_expression_token1,
  [1994] = 1,
    ACTIONS(314), 1,
      sym_string_content_sq,
  [1998] = 1,
    ACTIONS(316), 1,
      sym_string_content_dq,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 54,
  [SMALL_STATE(4)] = 108,
  [SMALL_STATE(5)] = 161,
  [SMALL_STATE(6)] = 214,
  [SMALL_STATE(7)] = 265,
  [SMALL_STATE(8)] = 316,
  [SMALL_STATE(9)] = 367,
  [SMALL_STATE(10)] = 418,
  [SMALL_STATE(11)] = 471,
  [SMALL_STATE(12)] = 524,
  [SMALL_STATE(13)] = 574,
  [SMALL_STATE(14)] = 622,
  [SMALL_STATE(15)] = 672,
  [SMALL_STATE(16)] = 722,
  [SMALL_STATE(17)] = 772,
  [SMALL_STATE(18)] = 822,
  [SMALL_STATE(19)] = 872,
  [SMALL_STATE(20)] = 922,
  [SMALL_STATE(21)] = 972,
  [SMALL_STATE(22)] = 1019,
  [SMALL_STATE(23)] = 1066,
  [SMALL_STATE(24)] = 1113,
  [SMALL_STATE(25)] = 1160,
  [SMALL_STATE(26)] = 1186,
  [SMALL_STATE(27)] = 1212,
  [SMALL_STATE(28)] = 1237,
  [SMALL_STATE(29)] = 1262,
  [SMALL_STATE(30)] = 1284,
  [SMALL_STATE(31)] = 1306,
  [SMALL_STATE(32)] = 1328,
  [SMALL_STATE(33)] = 1350,
  [SMALL_STATE(34)] = 1359,
  [SMALL_STATE(35)] = 1372,
  [SMALL_STATE(36)] = 1391,
  [SMALL_STATE(37)] = 1401,
  [SMALL_STATE(38)] = 1411,
  [SMALL_STATE(39)] = 1425,
  [SMALL_STATE(40)] = 1435,
  [SMALL_STATE(41)] = 1443,
  [SMALL_STATE(42)] = 1453,
  [SMALL_STATE(43)] = 1463,
  [SMALL_STATE(44)] = 1470,
  [SMALL_STATE(45)] = 1477,
  [SMALL_STATE(46)] = 1484,
  [SMALL_STATE(47)] = 1491,
  [SMALL_STATE(48)] = 1498,
  [SMALL_STATE(49)] = 1505,
  [SMALL_STATE(50)] = 1512,
  [SMALL_STATE(51)] = 1519,
  [SMALL_STATE(52)] = 1526,
  [SMALL_STATE(53)] = 1533,
  [SMALL_STATE(54)] = 1540,
  [SMALL_STATE(55)] = 1547,
  [SMALL_STATE(56)] = 1554,
  [SMALL_STATE(57)] = 1565,
  [SMALL_STATE(58)] = 1572,
  [SMALL_STATE(59)] = 1583,
  [SMALL_STATE(60)] = 1590,
  [SMALL_STATE(61)] = 1597,
  [SMALL_STATE(62)] = 1604,
  [SMALL_STATE(63)] = 1614,
  [SMALL_STATE(64)] = 1624,
  [SMALL_STATE(65)] = 1634,
  [SMALL_STATE(66)] = 1644,
  [SMALL_STATE(67)] = 1654,
  [SMALL_STATE(68)] = 1664,
  [SMALL_STATE(69)] = 1670,
  [SMALL_STATE(70)] = 1680,
  [SMALL_STATE(71)] = 1690,
  [SMALL_STATE(72)] = 1700,
  [SMALL_STATE(73)] = 1710,
  [SMALL_STATE(74)] = 1720,
  [SMALL_STATE(75)] = 1730,
  [SMALL_STATE(76)] = 1740,
  [SMALL_STATE(77)] = 1750,
  [SMALL_STATE(78)] = 1760,
  [SMALL_STATE(79)] = 1770,
  [SMALL_STATE(80)] = 1780,
  [SMALL_STATE(81)] = 1786,
  [SMALL_STATE(82)] = 1796,
  [SMALL_STATE(83)] = 1801,
  [SMALL_STATE(84)] = 1806,
  [SMALL_STATE(85)] = 1811,
  [SMALL_STATE(86)] = 1816,
  [SMALL_STATE(87)] = 1821,
  [SMALL_STATE(88)] = 1826,
  [SMALL_STATE(89)] = 1831,
  [SMALL_STATE(90)] = 1836,
  [SMALL_STATE(91)] = 1841,
  [SMALL_STATE(92)] = 1846,
  [SMALL_STATE(93)] = 1851,
  [SMALL_STATE(94)] = 1856,
  [SMALL_STATE(95)] = 1861,
  [SMALL_STATE(96)] = 1866,
  [SMALL_STATE(97)] = 1871,
  [SMALL_STATE(98)] = 1876,
  [SMALL_STATE(99)] = 1881,
  [SMALL_STATE(100)] = 1886,
  [SMALL_STATE(101)] = 1891,
  [SMALL_STATE(102)] = 1896,
  [SMALL_STATE(103)] = 1901,
  [SMALL_STATE(104)] = 1906,
  [SMALL_STATE(105)] = 1910,
  [SMALL_STATE(106)] = 1914,
  [SMALL_STATE(107)] = 1918,
  [SMALL_STATE(108)] = 1922,
  [SMALL_STATE(109)] = 1926,
  [SMALL_STATE(110)] = 1930,
  [SMALL_STATE(111)] = 1934,
  [SMALL_STATE(112)] = 1938,
  [SMALL_STATE(113)] = 1942,
  [SMALL_STATE(114)] = 1946,
  [SMALL_STATE(115)] = 1950,
  [SMALL_STATE(116)] = 1954,
  [SMALL_STATE(117)] = 1958,
  [SMALL_STATE(118)] = 1962,
  [SMALL_STATE(119)] = 1966,
  [SMALL_STATE(120)] = 1970,
  [SMALL_STATE(121)] = 1974,
  [SMALL_STATE(122)] = 1978,
  [SMALL_STATE(123)] = 1982,
  [SMALL_STATE(124)] = 1986,
  [SMALL_STATE(125)] = 1990,
  [SMALL_STATE(126)] = 1994,
  [SMALL_STATE(127)] = 1998,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(113),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(125),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(102),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [69] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [85] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [105] = {.entry = {.count = 1, .reusable = false}}, SHIFT(101),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [109] = {.entry = {.count = 1, .reusable = false}}, SHIFT(103),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [119] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [121] = {.entry = {.count = 1, .reusable = false}}, SHIFT(120),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [127] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(24),
  [130] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(113),
  [133] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(125),
  [136] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(41),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jinja_expression, 2),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jinja_expression, 2),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 1),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 3),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, .production_id = 2),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text, 1),
  [181] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_text, 1),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 3),
  [185] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 3),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple, 5),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dict, 5),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dict, 3),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 4),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple, 3),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple, 2),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 2),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 5),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 4),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dict, 2),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 2, .production_id = 1),
  [213] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2), SHIFT_REPEAT(22),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple, 4),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 5),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dict, 4),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 3),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [268] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2), SHIFT_REPEAT(13),
  [271] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [277] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_dict_repeat1, 2), SHIFT_REPEAT(35),
  [280] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_dict_repeat1, 2),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [286] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_kwarg, 3, .production_id = 3),
  [288] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pair, 3, .production_id = 3),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [306] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_double_quote, 1),
  [308] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_single_quote, 1),
  [310] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_jinja2(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
