#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 127
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 51
#define ALIAS_COUNT 0
#define TOKEN_COUNT 27
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 6
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 4

enum {
  anon_sym_LBRACE_LBRACE = 1,
  anon_sym_RBRACE_RBRACE = 2,
  sym__single_quote = 3,
  sym__double_quote = 4,
  sym_string_content_sq = 5,
  sym_string_content_dq = 6,
  sym_integer = 7,
  sym_float = 8,
  anon_sym_LBRACK = 9,
  anon_sym_COMMA = 10,
  anon_sym_RBRACK = 11,
  anon_sym_LPAREN = 12,
  anon_sym_RPAREN = 13,
  anon_sym_LBRACE = 14,
  anon_sym_RBRACE = 15,
  anon_sym_COLON = 16,
  sym_true = 17,
  sym_false = 18,
  sym_none = 19,
  anon_sym_LBRACE_PERCENT = 20,
  aux_sym_jinja_expression_token1 = 21,
  anon_sym_LBRACE_POUND = 22,
  aux_sym__jinja_comment_token1 = 23,
  sym__identifier = 24,
  anon_sym_EQ = 25,
  sym__text = 26,
  sym_source_file = 27,
  sym_statement = 28,
  sym_expression = 29,
  sym_comment = 30,
  sym_text = 31,
  sym__expression = 32,
  sym_string = 33,
  sym_single_quote = 34,
  sym_double_quote = 35,
  sym_list = 36,
  sym_tuple = 37,
  sym_dict = 38,
  sym_pair = 39,
  sym__bool = 40,
  sym_jinja_expression = 41,
  sym__jinja_comment = 42,
  sym_fn_call = 43,
  sym_argument_list = 44,
  sym_identifier = 45,
  sym_kwarg = 46,
  aux_sym_source_file_repeat1 = 47,
  aux_sym_list_repeat1 = 48,
  aux_sym_dict_repeat1 = 49,
  aux_sym_argument_list_repeat1 = 50,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACE_LBRACE] = "{{",
  [anon_sym_RBRACE_RBRACE] = "}}",
  [sym__single_quote] = "_single_quote",
  [sym__double_quote] = "_double_quote",
  [sym_string_content_sq] = "string_content_sq",
  [sym_string_content_dq] = "string_content_dq",
  [sym_integer] = "integer",
  [sym_float] = "float",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COLON] = ":",
  [sym_true] = "true",
  [sym_false] = "false",
  [sym_none] = "none",
  [anon_sym_LBRACE_PERCENT] = "{%",
  [aux_sym_jinja_expression_token1] = "jinja_expression_token1",
  [anon_sym_LBRACE_POUND] = "{#",
  [aux_sym__jinja_comment_token1] = "_jinja_comment_token1",
  [sym__identifier] = "_identifier",
  [anon_sym_EQ] = "=",
  [sym__text] = "_text",
  [sym_source_file] = "source_file",
  [sym_statement] = "statement",
  [sym_expression] = "expression",
  [sym_comment] = "comment",
  [sym_text] = "text",
  [sym__expression] = "_expression",
  [sym_string] = "string",
  [sym_single_quote] = "single_quote",
  [sym_double_quote] = "double_quote",
  [sym_list] = "list",
  [sym_tuple] = "tuple",
  [sym_dict] = "dict",
  [sym_pair] = "pair",
  [sym__bool] = "_bool",
  [sym_jinja_expression] = "jinja_expression",
  [sym__jinja_comment] = "_jinja_comment",
  [sym_fn_call] = "fn_call",
  [sym_argument_list] = "argument_list",
  [sym_identifier] = "identifier",
  [sym_kwarg] = "kwarg",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_list_repeat1] = "list_repeat1",
  [aux_sym_dict_repeat1] = "dict_repeat1",
  [aux_sym_argument_list_repeat1] = "argument_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACE_LBRACE] = anon_sym_LBRACE_LBRACE,
  [anon_sym_RBRACE_RBRACE] = anon_sym_RBRACE_RBRACE,
  [sym__single_quote] = sym__single_quote,
  [sym__double_quote] = sym__double_quote,
  [sym_string_content_sq] = sym_string_content_sq,
  [sym_string_content_dq] = sym_string_content_dq,
  [sym_integer] = sym_integer,
  [sym_float] = sym_float,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_true] = sym_true,
  [sym_false] = sym_false,
  [sym_none] = sym_none,
  [anon_sym_LBRACE_PERCENT] = anon_sym_LBRACE_PERCENT,
  [aux_sym_jinja_expression_token1] = aux_sym_jinja_expression_token1,
  [anon_sym_LBRACE_POUND] = anon_sym_LBRACE_POUND,
  [aux_sym__jinja_comment_token1] = aux_sym__jinja_comment_token1,
  [sym__identifier] = sym__identifier,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym__text] = sym__text,
  [sym_source_file] = sym_source_file,
  [sym_statement] = sym_statement,
  [sym_expression] = sym_expression,
  [sym_comment] = sym_comment,
  [sym_text] = sym_text,
  [sym__expression] = sym__expression,
  [sym_string] = sym_string,
  [sym_single_quote] = sym_single_quote,
  [sym_double_quote] = sym_double_quote,
  [sym_list] = sym_list,
  [sym_tuple] = sym_tuple,
  [sym_dict] = sym_dict,
  [sym_pair] = sym_pair,
  [sym__bool] = sym__bool,
  [sym_jinja_expression] = sym_jinja_expression,
  [sym__jinja_comment] = sym__jinja_comment,
  [sym_fn_call] = sym_fn_call,
  [sym_argument_list] = sym_argument_list,
  [sym_identifier] = sym_identifier,
  [sym_kwarg] = sym_kwarg,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_list_repeat1] = aux_sym_list_repeat1,
  [aux_sym_dict_repeat1] = aux_sym_dict_repeat1,
  [aux_sym_argument_list_repeat1] = aux_sym_argument_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym__single_quote] = {
    .visible = false,
    .named = true,
  },
  [sym__double_quote] = {
    .visible = false,
    .named = true,
  },
  [sym_string_content_sq] = {
    .visible = true,
    .named = true,
  },
  [sym_string_content_dq] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_true] = {
    .visible = true,
    .named = true,
  },
  [sym_false] = {
    .visible = true,
    .named = true,
  },
  [sym_none] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_jinja_expression_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACE_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__jinja_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym__identifier] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym__text] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_single_quote] = {
    .visible = true,
    .named = true,
  },
  [sym_double_quote] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym_tuple] = {
    .visible = true,
    .named = true,
  },
  [sym_dict] = {
    .visible = true,
    .named = true,
  },
  [sym_pair] = {
    .visible = true,
    .named = true,
  },
  [sym__bool] = {
    .visible = false,
    .named = true,
  },
  [sym_jinja_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__jinja_comment] = {
    .visible = false,
    .named = true,
  },
  [sym_fn_call] = {
    .visible = true,
    .named = true,
  },
  [sym_argument_list] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_kwarg] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_dict_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_argument_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_argument_list = 1,
  field_fn_name = 2,
  field_key = 3,
  field_quote_type = 4,
  field_string_content = 5,
  field_value = 6,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_argument_list] = "argument_list",
  [field_fn_name] = "fn_name",
  [field_key] = "key",
  [field_quote_type] = "quote_type",
  [field_string_content] = "string_content",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 2},
  [3] = {.index = 4, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_argument_list, 1},
    {field_fn_name, 0},
  [2] =
    {field_quote_type, 0},
    {field_string_content, 1},
  [4] =
    {field_key, 0},
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 6,
  [8] = 5,
  [9] = 4,
  [10] = 10,
  [11] = 10,
  [12] = 12,
  [13] = 13,
  [14] = 13,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 15,
  [19] = 12,
  [20] = 17,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 27,
  [29] = 29,
  [30] = 30,
  [31] = 29,
  [32] = 30,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 63,
  [66] = 62,
  [67] = 67,
  [68] = 64,
  [69] = 67,
  [70] = 70,
  [71] = 70,
  [72] = 72,
  [73] = 72,
  [74] = 60,
  [75] = 75,
  [76] = 76,
  [77] = 75,
  [78] = 78,
  [79] = 51,
  [80] = 52,
  [81] = 45,
  [82] = 41,
  [83] = 55,
  [84] = 47,
  [85] = 46,
  [86] = 42,
  [87] = 44,
  [88] = 37,
  [89] = 50,
  [90] = 53,
  [91] = 57,
  [92] = 92,
  [93] = 43,
  [94] = 48,
  [95] = 49,
  [96] = 54,
  [97] = 58,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 92,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 105,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 109,
  [113] = 113,
  [114] = 110,
  [115] = 115,
  [116] = 116,
  [117] = 116,
  [118] = 118,
  [119] = 106,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 104,
  [124] = 124,
  [125] = 113,
  [126] = 111,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(17);
      if (lookahead == '"') ADVANCE(21);
      if (lookahead == '\'') ADVANCE(20);
      if (lookahead == '(') ADVANCE(39);
      if (lookahead == ')') ADVANCE(40);
      if (lookahead == ',') ADVANCE(37);
      if (lookahead == '.') ADVANCE(13);
      if (lookahead == ':') ADVANCE(44);
      if (lookahead == '=') ADVANCE(64);
      if (lookahead == '[') ADVANCE(36);
      if (lookahead == ']') ADVANCE(38);
      if (lookahead == '{') ADVANCE(42);
      if (lookahead == '}') ADVANCE(43);
      if (('+' <= lookahead && lookahead <= '-')) ADVANCE(9);
      if (lookahead == 'F' ||
          lookahead == 'f') ADVANCE(53);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(59);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(60);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(21);
      if (lookahead == '\'') ADVANCE(20);
      if (lookahead == '(') ADVANCE(39);
      if (lookahead == ')') ADVANCE(40);
      if (lookahead == ',') ADVANCE(37);
      if (lookahead == '.') ADVANCE(13);
      if (lookahead == ':') ADVANCE(44);
      if (lookahead == '[') ADVANCE(36);
      if (lookahead == ']') ADVANCE(38);
      if (lookahead == '{') ADVANCE(41);
      if (lookahead == '}') ADVANCE(10);
      if (('+' <= lookahead && lookahead <= '-')) ADVANCE(9);
      if (lookahead == 'F' ||
          lookahead == 'f') ADVANCE(53);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(59);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(60);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 2:
      if (lookahead == '#') ADVANCE(50);
      if (lookahead == '%') ADVANCE(48);
      if (lookahead == '{') ADVANCE(18);
      if (lookahead != 0) ADVANCE(66);
      END_STATE();
    case 3:
      if (lookahead == '#') ADVANCE(6);
      if (lookahead == '}') ADVANCE(52);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 4:
      if (lookahead == '#') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(4);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '#') ADVANCE(6);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '#') ADVANCE(3);
      if (lookahead == '}') ADVANCE(51);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 7:
      if (lookahead == '%') ADVANCE(11);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(7);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 8:
      if (lookahead == '%') ADVANCE(11);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 9:
      if (lookahead == '.') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      END_STATE();
    case 10:
      if (lookahead == '}') ADVANCE(19);
      END_STATE();
    case 11:
      if (lookahead == '}') ADVANCE(49);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 12:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      END_STATE();
    case 13:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 14:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      END_STATE();
    case 15:
      if (lookahead != 0 &&
          lookahead != '#' &&
          lookahead != '%' &&
          lookahead != '{') ADVANCE(66);
      END_STATE();
    case 16:
      if (eof) ADVANCE(17);
      if (lookahead == '{') ADVANCE(2);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(65);
      if (lookahead != 0) ADVANCE(66);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym__single_quote);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym__double_quote);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_string_content_sq);
      if (lookahead == '\\') ADVANCE(24);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(23);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_string_content_sq);
      if (lookahead == '\\') ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_string_content_sq);
      if (lookahead != 0 &&
          lookahead != '\\') ADVANCE(23);
      if (lookahead == '\\') ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_string_content_dq);
      if (lookahead == '\\') ADVANCE(27);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(26);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_string_content_dq);
      if (lookahead == '\\') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_string_content_dq);
      if (lookahead != 0 &&
          lookahead != '\\') ADVANCE(26);
      if (lookahead == '\\') ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '.') ADVANCE(34);
      if (lookahead == '_') ADVANCE(30);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '.') ADVANCE(34);
      if (lookahead == '_') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '.') ADVANCE(34);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '.') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_float);
      if (lookahead == '_') ADVANCE(34);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_float);
      if (lookahead == '_') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_float);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_float);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead == '#') ADVANCE(50);
      if (lookahead == '%') ADVANCE(48);
      if (lookahead == '{') ADVANCE(18);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_true);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_false);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_none);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_LBRACE_PERCENT);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_jinja_expression_token1);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_LBRACE_POUND);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym__jinja_comment_token1);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym__jinja_comment_token1);
      if (lookahead == '#') ADVANCE(6);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead == 'a') ADVANCE(57);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead == 'e') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead == 'e') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead == 'e') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead == 'l') ADVANCE(61);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead == 'n') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead == 'o') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead == 'r') ADVANCE(62);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead == 's') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead == 'u') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym__identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym__text);
      if (lookahead == '{') ADVANCE(2);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(65);
      if (lookahead != 0) ADVANCE(66);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym__text);
      if (lookahead == '{') ADVANCE(15);
      if (lookahead != 0) ADVANCE(66);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 16},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 16},
  [26] = {.lex_state = 16},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 16},
  [35] = {.lex_state = 16},
  [36] = {.lex_state = 16},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 16},
  [39] = {.lex_state = 16},
  [40] = {.lex_state = 16},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 1},
  [58] = {.lex_state = 1},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 25},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 22},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 1},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 7},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 25},
  [121] = {.lex_state = 22},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 4},
  [125] = {.lex_state = 22},
  [126] = {.lex_state = 25},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(1),
    [sym__single_quote] = ACTIONS(1),
    [sym__double_quote] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [sym_float] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_true] = ACTIONS(1),
    [sym_false] = ACTIONS(1),
    [sym_none] = ACTIONS(1),
    [anon_sym_LBRACE_PERCENT] = ACTIONS(1),
    [anon_sym_LBRACE_POUND] = ACTIONS(1),
    [sym__identifier] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(122),
    [sym_statement] = STATE(26),
    [sym_expression] = STATE(26),
    [sym_comment] = STATE(26),
    [sym_text] = STATE(26),
    [sym_jinja_expression] = STATE(39),
    [sym__jinja_comment] = STATE(40),
    [aux_sym_source_file_repeat1] = STATE(26),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(5),
    [anon_sym_LBRACE_PERCENT] = ACTIONS(7),
    [anon_sym_LBRACE_POUND] = ACTIONS(9),
    [sym__text] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 14,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(19), 1,
      sym_float,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_COMMA,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      anon_sym_RPAREN,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym__identifier,
    STATE(78), 1,
      sym_identifier,
    STATE(111), 1,
      sym_double_quote,
    STATE(113), 1,
      sym_single_quote,
    ACTIONS(17), 4,
      sym_integer,
      sym_true,
      sym_false,
      sym_none,
    STATE(65), 8,
      sym__expression,
      sym_string,
      sym_list,
      sym_tuple,
      sym_dict,
      sym__bool,
      sym_fn_call,
      sym_kwarg,
  [53] = 14,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym__identifier,
    ACTIONS(35), 1,
      sym_float,
    ACTIONS(37), 1,
      anon_sym_COMMA,
    ACTIONS(39), 1,
      anon_sym_RPAREN,
    STATE(78), 1,
      sym_identifier,
    STATE(111), 1,
      sym_double_quote,
    STATE(113), 1,
      sym_single_quote,
    ACTIONS(33), 4,
      sym_integer,
      sym_true,
      sym_false,
      sym_none,
    STATE(63), 8,
      sym__expression,
      sym_string,
      sym_list,
      sym_tuple,
      sym_dict,
      sym__bool,
      sym_fn_call,
      sym_kwarg,
  [106] = 14,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym__identifier,
    ACTIONS(43), 1,
      sym_float,
    ACTIONS(45), 1,
      anon_sym_COMMA,
    ACTIONS(47), 1,
      anon_sym_RBRACK,
    STATE(92), 1,
      sym_identifier,
    STATE(111), 1,
      sym_double_quote,
    STATE(113), 1,
      sym_single_quote,
    ACTIONS(41), 4,
      sym_integer,
      sym_true,
      sym_false,
      sym_none,
    STATE(77), 7,
      sym__expression,
      sym_string,
      sym_list,
      sym_tuple,
      sym_dict,
      sym__bool,
      sym_fn_call,
  [158] = 13,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym__identifier,
    ACTIONS(51), 1,
      sym_float,
    ACTIONS(53), 1,
      anon_sym_RPAREN,
    STATE(78), 1,
      sym_identifier,
    STATE(111), 1,
      sym_double_quote,
    STATE(113), 1,
      sym_single_quote,
    ACTIONS(49), 4,
      sym_integer,
      sym_true,
      sym_false,
      sym_none,
    STATE(102), 8,
      sym__expression,
      sym_string,
      sym_list,
      sym_tuple,
      sym_dict,
      sym__bool,
      sym_fn_call,
      sym_kwarg,
  [208] = 13,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym__identifier,
    ACTIONS(51), 1,
      sym_float,
    ACTIONS(55), 1,
      anon_sym_RPAREN,
    STATE(78), 1,
      sym_identifier,
    STATE(111), 1,
      sym_double_quote,
    STATE(113), 1,
      sym_single_quote,
    ACTIONS(49), 4,
      sym_integer,
      sym_true,
      sym_false,
      sym_none,
    STATE(102), 8,
      sym__expression,
      sym_string,
      sym_list,
      sym_tuple,
      sym_dict,
      sym__bool,
      sym_fn_call,
      sym_kwarg,
  [258] = 13,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym__identifier,
    ACTIONS(51), 1,
      sym_float,
    ACTIONS(57), 1,
      anon_sym_RPAREN,
    STATE(78), 1,
      sym_identifier,
    STATE(111), 1,
      sym_double_quote,
    STATE(113), 1,
      sym_single_quote,
    ACTIONS(49), 4,
      sym_integer,
      sym_true,
      sym_false,
      sym_none,
    STATE(102), 8,
      sym__expression,
      sym_string,
      sym_list,
      sym_tuple,
      sym_dict,
      sym__bool,
      sym_fn_call,
      sym_kwarg,
  [308] = 13,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym__identifier,
    ACTIONS(51), 1,
      sym_float,
    ACTIONS(59), 1,
      anon_sym_RPAREN,
    STATE(78), 1,
      sym_identifier,
    STATE(111), 1,
      sym_double_quote,
    STATE(113), 1,
      sym_single_quote,
    ACTIONS(49), 4,
      sym_integer,
      sym_true,
      sym_false,
      sym_none,
    STATE(102), 8,
      sym__expression,
      sym_string,
      sym_list,
      sym_tuple,
      sym_dict,
      sym__bool,
      sym_fn_call,
      sym_kwarg,
  [358] = 14,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym__identifier,
    ACTIONS(63), 1,
      sym_float,
    ACTIONS(65), 1,
      anon_sym_COMMA,
    ACTIONS(67), 1,
      anon_sym_RBRACK,
    STATE(92), 1,
      sym_identifier,
    STATE(111), 1,
      sym_double_quote,
    STATE(113), 1,
      sym_single_quote,
    ACTIONS(61), 4,
      sym_integer,
      sym_true,
      sym_false,
      sym_none,
    STATE(75), 7,
      sym__expression,
      sym_string,
      sym_list,
      sym_tuple,
      sym_dict,
      sym__bool,
      sym_fn_call,
  [410] = 14,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym__identifier,
    ACTIONS(71), 1,
      sym_float,
    ACTIONS(73), 1,
      anon_sym_COMMA,
    ACTIONS(75), 1,
      anon_sym_RPAREN,
    STATE(92), 1,
      sym_identifier,
    STATE(111), 1,
      sym_double_quote,
    STATE(113), 1,
      sym_single_quote,
    ACTIONS(69), 4,
      sym_integer,
      sym_true,
      sym_false,
      sym_none,
    STATE(74), 7,
      sym__expression,
      sym_string,
      sym_list,
      sym_tuple,
      sym_dict,
      sym__bool,
      sym_fn_call,
  [462] = 14,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym__identifier,
    ACTIONS(79), 1,
      sym_float,
    ACTIONS(81), 1,
      anon_sym_COMMA,
    ACTIONS(83), 1,
      anon_sym_RPAREN,
    STATE(92), 1,
      sym_identifier,
    STATE(111), 1,
      sym_double_quote,
    STATE(113), 1,
      sym_single_quote,
    ACTIONS(77), 4,
      sym_integer,
      sym_true,
      sym_false,
      sym_none,
    STATE(60), 7,
      sym__expression,
      sym_string,
      sym_list,
      sym_tuple,
      sym_dict,
      sym__bool,
      sym_fn_call,
  [514] = 13,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym__identifier,
    ACTIONS(87), 1,
      sym_float,
    ACTIONS(89), 1,
      anon_sym_RPAREN,
    STATE(92), 1,
      sym_identifier,
    STATE(111), 1,
      sym_double_quote,
    STATE(113), 1,
      sym_single_quote,
    ACTIONS(85), 4,
      sym_integer,
      sym_true,
      sym_false,
      sym_none,
    STATE(61), 7,
      sym__expression,
      sym_string,
      sym_list,
      sym_tuple,
      sym_dict,
      sym__bool,
      sym_fn_call,
  [563] = 13,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym__identifier,
    ACTIONS(87), 1,
      sym_float,
    ACTIONS(91), 1,
      anon_sym_RBRACK,
    STATE(92), 1,
      sym_identifier,
    STATE(111), 1,
      sym_double_quote,
    STATE(113), 1,
      sym_single_quote,
    ACTIONS(85), 4,
      sym_integer,
      sym_true,
      sym_false,
      sym_none,
    STATE(61), 7,
      sym__expression,
      sym_string,
      sym_list,
      sym_tuple,
      sym_dict,
      sym__bool,
      sym_fn_call,
  [612] = 13,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym__identifier,
    ACTIONS(87), 1,
      sym_float,
    ACTIONS(93), 1,
      anon_sym_RBRACK,
    STATE(92), 1,
      sym_identifier,
    STATE(111), 1,
      sym_double_quote,
    STATE(113), 1,
      sym_single_quote,
    ACTIONS(85), 4,
      sym_integer,
      sym_true,
      sym_false,
      sym_none,
    STATE(61), 7,
      sym__expression,
      sym_string,
      sym_list,
      sym_tuple,
      sym_dict,
      sym__bool,
      sym_fn_call,
  [661] = 13,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym__identifier,
    ACTIONS(87), 1,
      sym_float,
    ACTIONS(95), 1,
      anon_sym_RBRACK,
    STATE(92), 1,
      sym_identifier,
    STATE(111), 1,
      sym_double_quote,
    STATE(113), 1,
      sym_single_quote,
    ACTIONS(85), 4,
      sym_integer,
      sym_true,
      sym_false,
      sym_none,
    STATE(61), 7,
      sym__expression,
      sym_string,
      sym_list,
      sym_tuple,
      sym_dict,
      sym__bool,
      sym_fn_call,
  [710] = 12,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym__identifier,
    ACTIONS(51), 1,
      sym_float,
    STATE(78), 1,
      sym_identifier,
    STATE(111), 1,
      sym_double_quote,
    STATE(113), 1,
      sym_single_quote,
    ACTIONS(49), 4,
      sym_integer,
      sym_true,
      sym_false,
      sym_none,
    STATE(102), 8,
      sym__expression,
      sym_string,
      sym_list,
      sym_tuple,
      sym_dict,
      sym__bool,
      sym_fn_call,
      sym_kwarg,
  [757] = 13,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym__identifier,
    ACTIONS(87), 1,
      sym_float,
    ACTIONS(97), 1,
      anon_sym_RPAREN,
    STATE(92), 1,
      sym_identifier,
    STATE(111), 1,
      sym_double_quote,
    STATE(113), 1,
      sym_single_quote,
    ACTIONS(85), 4,
      sym_integer,
      sym_true,
      sym_false,
      sym_none,
    STATE(61), 7,
      sym__expression,
      sym_string,
      sym_list,
      sym_tuple,
      sym_dict,
      sym__bool,
      sym_fn_call,
  [806] = 13,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym__identifier,
    ACTIONS(87), 1,
      sym_float,
    ACTIONS(99), 1,
      anon_sym_RBRACK,
    STATE(92), 1,
      sym_identifier,
    STATE(111), 1,
      sym_double_quote,
    STATE(113), 1,
      sym_single_quote,
    ACTIONS(85), 4,
      sym_integer,
      sym_true,
      sym_false,
      sym_none,
    STATE(61), 7,
      sym__expression,
      sym_string,
      sym_list,
      sym_tuple,
      sym_dict,
      sym__bool,
      sym_fn_call,
  [855] = 13,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym__identifier,
    ACTIONS(87), 1,
      sym_float,
    ACTIONS(101), 1,
      anon_sym_RPAREN,
    STATE(92), 1,
      sym_identifier,
    STATE(111), 1,
      sym_double_quote,
    STATE(113), 1,
      sym_single_quote,
    ACTIONS(85), 4,
      sym_integer,
      sym_true,
      sym_false,
      sym_none,
    STATE(61), 7,
      sym__expression,
      sym_string,
      sym_list,
      sym_tuple,
      sym_dict,
      sym__bool,
      sym_fn_call,
  [904] = 13,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym__identifier,
    ACTIONS(87), 1,
      sym_float,
    ACTIONS(103), 1,
      anon_sym_RPAREN,
    STATE(92), 1,
      sym_identifier,
    STATE(111), 1,
      sym_double_quote,
    STATE(113), 1,
      sym_single_quote,
    ACTIONS(85), 4,
      sym_integer,
      sym_true,
      sym_false,
      sym_none,
    STATE(61), 7,
      sym__expression,
      sym_string,
      sym_list,
      sym_tuple,
      sym_dict,
      sym__bool,
      sym_fn_call,
  [953] = 12,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym__identifier,
    ACTIONS(87), 1,
      sym_float,
    STATE(92), 1,
      sym_identifier,
    STATE(111), 1,
      sym_double_quote,
    STATE(113), 1,
      sym_single_quote,
    ACTIONS(85), 4,
      sym_integer,
      sym_true,
      sym_false,
      sym_none,
    STATE(61), 7,
      sym__expression,
      sym_string,
      sym_list,
      sym_tuple,
      sym_dict,
      sym__bool,
      sym_fn_call,
  [999] = 12,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym__identifier,
    ACTIONS(107), 1,
      sym_float,
    STATE(92), 1,
      sym_identifier,
    STATE(111), 1,
      sym_double_quote,
    STATE(113), 1,
      sym_single_quote,
    ACTIONS(105), 4,
      sym_integer,
      sym_true,
      sym_false,
      sym_none,
    STATE(115), 7,
      sym__expression,
      sym_string,
      sym_list,
      sym_tuple,
      sym_dict,
      sym__bool,
      sym_fn_call,
  [1045] = 12,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(31), 1,
      sym__identifier,
    ACTIONS(111), 1,
      sym_float,
    ACTIONS(113), 1,
      anon_sym_LBRACK,
    ACTIONS(115), 1,
      anon_sym_LPAREN,
    ACTIONS(117), 1,
      anon_sym_LBRACE,
    STATE(101), 1,
      sym_identifier,
    STATE(125), 1,
      sym_single_quote,
    STATE(126), 1,
      sym_double_quote,
    ACTIONS(109), 4,
      sym_integer,
      sym_true,
      sym_false,
      sym_none,
    STATE(99), 7,
      sym__expression,
      sym_string,
      sym_list,
      sym_tuple,
      sym_dict,
      sym__bool,
      sym_fn_call,
  [1091] = 12,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym__identifier,
    ACTIONS(121), 1,
      sym_float,
    STATE(92), 1,
      sym_identifier,
    STATE(111), 1,
      sym_double_quote,
    STATE(113), 1,
      sym_single_quote,
    ACTIONS(119), 4,
      sym_integer,
      sym_true,
      sym_false,
      sym_none,
    STATE(103), 7,
      sym__expression,
      sym_string,
      sym_list,
      sym_tuple,
      sym_dict,
      sym__bool,
      sym_fn_call,
  [1137] = 8,
    ACTIONS(123), 1,
      ts_builtin_sym_end,
    ACTIONS(125), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(128), 1,
      anon_sym_LBRACE_PERCENT,
    ACTIONS(131), 1,
      anon_sym_LBRACE_POUND,
    ACTIONS(134), 1,
      sym__text,
    STATE(39), 1,
      sym_jinja_expression,
    STATE(40), 1,
      sym__jinja_comment,
    STATE(25), 5,
      sym_statement,
      sym_expression,
      sym_comment,
      sym_text,
      aux_sym_source_file_repeat1,
  [1166] = 8,
    ACTIONS(5), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(7), 1,
      anon_sym_LBRACE_PERCENT,
    ACTIONS(9), 1,
      anon_sym_LBRACE_POUND,
    ACTIONS(11), 1,
      sym__text,
    ACTIONS(137), 1,
      ts_builtin_sym_end,
    STATE(39), 1,
      sym_jinja_expression,
    STATE(40), 1,
      sym__jinja_comment,
    STATE(25), 5,
      sym_statement,
      sym_expression,
      sym_comment,
      sym_text,
      aux_sym_source_file_repeat1,
  [1195] = 8,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(139), 1,
      anon_sym_COMMA,
    ACTIONS(141), 1,
      anon_sym_RBRACE,
    STATE(72), 1,
      sym_pair,
    STATE(107), 1,
      sym_string,
    STATE(111), 1,
      sym_double_quote,
    STATE(113), 1,
      sym_single_quote,
  [1220] = 8,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(143), 1,
      anon_sym_COMMA,
    ACTIONS(145), 1,
      anon_sym_RBRACE,
    STATE(73), 1,
      sym_pair,
    STATE(107), 1,
      sym_string,
    STATE(111), 1,
      sym_double_quote,
    STATE(113), 1,
      sym_single_quote,
  [1245] = 7,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(147), 1,
      anon_sym_RBRACE,
    STATE(98), 1,
      sym_pair,
    STATE(107), 1,
      sym_string,
    STATE(111), 1,
      sym_double_quote,
    STATE(113), 1,
      sym_single_quote,
  [1267] = 7,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(149), 1,
      anon_sym_RBRACE,
    STATE(98), 1,
      sym_pair,
    STATE(107), 1,
      sym_string,
    STATE(111), 1,
      sym_double_quote,
    STATE(113), 1,
      sym_single_quote,
  [1289] = 7,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(151), 1,
      anon_sym_RBRACE,
    STATE(98), 1,
      sym_pair,
    STATE(107), 1,
      sym_string,
    STATE(111), 1,
      sym_double_quote,
    STATE(113), 1,
      sym_single_quote,
  [1311] = 7,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(153), 1,
      anon_sym_RBRACE,
    STATE(98), 1,
      sym_pair,
    STATE(107), 1,
      sym_string,
    STATE(111), 1,
      sym_double_quote,
    STATE(113), 1,
      sym_single_quote,
  [1333] = 6,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    STATE(98), 1,
      sym_pair,
    STATE(107), 1,
      sym_string,
    STATE(111), 1,
      sym_double_quote,
    STATE(113), 1,
      sym_single_quote,
  [1352] = 2,
    ACTIONS(155), 2,
      ts_builtin_sym_end,
      sym__text,
    ACTIONS(157), 3,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_POUND,
  [1362] = 2,
    ACTIONS(159), 2,
      ts_builtin_sym_end,
      sym__text,
    ACTIONS(161), 3,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_POUND,
  [1372] = 2,
    ACTIONS(163), 2,
      ts_builtin_sym_end,
      sym__text,
    ACTIONS(165), 3,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_POUND,
  [1382] = 1,
    ACTIONS(167), 5,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_COLON,
  [1390] = 2,
    ACTIONS(169), 2,
      ts_builtin_sym_end,
      sym__text,
    ACTIONS(171), 3,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_POUND,
  [1400] = 2,
    ACTIONS(173), 2,
      ts_builtin_sym_end,
      sym__text,
    ACTIONS(175), 3,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_POUND,
  [1410] = 2,
    ACTIONS(177), 2,
      ts_builtin_sym_end,
      sym__text,
    ACTIONS(179), 3,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_POUND,
  [1420] = 1,
    ACTIONS(181), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1427] = 1,
    ACTIONS(183), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1434] = 1,
    ACTIONS(185), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1441] = 1,
    ACTIONS(187), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1448] = 1,
    ACTIONS(189), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1455] = 1,
    ACTIONS(191), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1462] = 1,
    ACTIONS(193), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1469] = 1,
    ACTIONS(195), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1476] = 1,
    ACTIONS(197), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1483] = 1,
    ACTIONS(199), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1490] = 1,
    ACTIONS(201), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1497] = 1,
    ACTIONS(203), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1504] = 1,
    ACTIONS(205), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1511] = 1,
    ACTIONS(207), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1518] = 1,
    ACTIONS(209), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1525] = 3,
    ACTIONS(211), 1,
      anon_sym_COMMA,
    STATE(56), 1,
      aux_sym_list_repeat1,
    ACTIONS(214), 2,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1536] = 1,
    ACTIONS(216), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1543] = 1,
    ACTIONS(218), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1550] = 3,
    ACTIONS(220), 1,
      anon_sym_COMMA,
    ACTIONS(223), 1,
      anon_sym_RBRACE,
    STATE(59), 1,
      aux_sym_dict_repeat1,
  [1560] = 3,
    ACTIONS(225), 1,
      anon_sym_COMMA,
    ACTIONS(227), 1,
      anon_sym_RPAREN,
    STATE(69), 1,
      aux_sym_list_repeat1,
  [1570] = 1,
    ACTIONS(214), 3,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1576] = 3,
    ACTIONS(55), 1,
      anon_sym_RPAREN,
    ACTIONS(229), 1,
      anon_sym_COMMA,
    STATE(76), 1,
      aux_sym_argument_list_repeat1,
  [1586] = 3,
    ACTIONS(231), 1,
      anon_sym_COMMA,
    ACTIONS(233), 1,
      anon_sym_RPAREN,
    STATE(62), 1,
      aux_sym_argument_list_repeat1,
  [1596] = 3,
    ACTIONS(147), 1,
      anon_sym_RBRACE,
    ACTIONS(235), 1,
      anon_sym_COMMA,
    STATE(59), 1,
      aux_sym_dict_repeat1,
  [1606] = 3,
    ACTIONS(237), 1,
      anon_sym_COMMA,
    ACTIONS(239), 1,
      anon_sym_RPAREN,
    STATE(66), 1,
      aux_sym_argument_list_repeat1,
  [1616] = 3,
    ACTIONS(57), 1,
      anon_sym_RPAREN,
    ACTIONS(241), 1,
      anon_sym_COMMA,
    STATE(76), 1,
      aux_sym_argument_list_repeat1,
  [1626] = 3,
    ACTIONS(97), 1,
      anon_sym_RPAREN,
    ACTIONS(243), 1,
      anon_sym_COMMA,
    STATE(56), 1,
      aux_sym_list_repeat1,
  [1636] = 3,
    ACTIONS(151), 1,
      anon_sym_RBRACE,
    ACTIONS(245), 1,
      anon_sym_COMMA,
    STATE(59), 1,
      aux_sym_dict_repeat1,
  [1646] = 3,
    ACTIONS(103), 1,
      anon_sym_RPAREN,
    ACTIONS(247), 1,
      anon_sym_COMMA,
    STATE(56), 1,
      aux_sym_list_repeat1,
  [1656] = 3,
    ACTIONS(95), 1,
      anon_sym_RBRACK,
    ACTIONS(249), 1,
      anon_sym_COMMA,
    STATE(56), 1,
      aux_sym_list_repeat1,
  [1666] = 3,
    ACTIONS(99), 1,
      anon_sym_RBRACK,
    ACTIONS(251), 1,
      anon_sym_COMMA,
    STATE(56), 1,
      aux_sym_list_repeat1,
  [1676] = 3,
    ACTIONS(253), 1,
      anon_sym_COMMA,
    ACTIONS(255), 1,
      anon_sym_RBRACE,
    STATE(64), 1,
      aux_sym_dict_repeat1,
  [1686] = 3,
    ACTIONS(257), 1,
      anon_sym_COMMA,
    ACTIONS(259), 1,
      anon_sym_RBRACE,
    STATE(68), 1,
      aux_sym_dict_repeat1,
  [1696] = 3,
    ACTIONS(261), 1,
      anon_sym_COMMA,
    ACTIONS(263), 1,
      anon_sym_RPAREN,
    STATE(67), 1,
      aux_sym_list_repeat1,
  [1706] = 3,
    ACTIONS(265), 1,
      anon_sym_COMMA,
    ACTIONS(267), 1,
      anon_sym_RBRACK,
    STATE(71), 1,
      aux_sym_list_repeat1,
  [1716] = 3,
    ACTIONS(269), 1,
      anon_sym_COMMA,
    ACTIONS(272), 1,
      anon_sym_RPAREN,
    STATE(76), 1,
      aux_sym_argument_list_repeat1,
  [1726] = 3,
    ACTIONS(274), 1,
      anon_sym_COMMA,
    ACTIONS(276), 1,
      anon_sym_RBRACK,
    STATE(70), 1,
      aux_sym_list_repeat1,
  [1736] = 3,
    ACTIONS(278), 1,
      anon_sym_LPAREN,
    ACTIONS(280), 1,
      anon_sym_EQ,
    STATE(47), 1,
      sym_argument_list,
  [1746] = 1,
    ACTIONS(201), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1751] = 1,
    ACTIONS(203), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1756] = 1,
    ACTIONS(189), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1761] = 1,
    ACTIONS(181), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1766] = 1,
    ACTIONS(209), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1771] = 1,
    ACTIONS(193), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1776] = 1,
    ACTIONS(191), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1781] = 1,
    ACTIONS(183), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1786] = 1,
    ACTIONS(187), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1791] = 1,
    ACTIONS(167), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1796] = 1,
    ACTIONS(199), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1801] = 1,
    ACTIONS(205), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1806] = 1,
    ACTIONS(216), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1811] = 2,
    ACTIONS(278), 1,
      anon_sym_LPAREN,
    STATE(47), 1,
      sym_argument_list,
  [1818] = 1,
    ACTIONS(185), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1823] = 1,
    ACTIONS(195), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1828] = 1,
    ACTIONS(197), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1833] = 1,
    ACTIONS(207), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1838] = 1,
    ACTIONS(218), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1843] = 1,
    ACTIONS(223), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1848] = 1,
    ACTIONS(282), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1853] = 1,
    ACTIONS(284), 2,
      anon_sym_LPAREN,
      anon_sym_EQ,
  [1858] = 2,
    ACTIONS(286), 1,
      anon_sym_LPAREN,
    STATE(84), 1,
      sym_argument_list,
  [1865] = 1,
    ACTIONS(272), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1870] = 1,
    ACTIONS(288), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1875] = 1,
    ACTIONS(267), 1,
      anon_sym_RBRACK,
  [1879] = 1,
    ACTIONS(259), 1,
      anon_sym_RBRACE,
  [1883] = 1,
    ACTIONS(263), 1,
      anon_sym_RPAREN,
  [1887] = 1,
    ACTIONS(290), 1,
      anon_sym_COLON,
  [1891] = 1,
    ACTIONS(255), 1,
      anon_sym_RBRACE,
  [1895] = 1,
    ACTIONS(292), 1,
      sym__single_quote,
  [1899] = 1,
    ACTIONS(292), 1,
      sym__double_quote,
  [1903] = 1,
    ACTIONS(294), 1,
      sym_string_content_dq,
  [1907] = 1,
    ACTIONS(296), 1,
      sym__single_quote,
  [1911] = 1,
    ACTIONS(298), 1,
      sym_string_content_sq,
  [1915] = 1,
    ACTIONS(296), 1,
      sym__double_quote,
  [1919] = 1,
    ACTIONS(300), 1,
      anon_sym_RBRACE_RBRACE,
  [1923] = 1,
    ACTIONS(239), 1,
      anon_sym_RPAREN,
  [1927] = 1,
    ACTIONS(233), 1,
      anon_sym_RPAREN,
  [1931] = 1,
    ACTIONS(302), 1,
      aux_sym_jinja_expression_token1,
  [1935] = 1,
    ACTIONS(227), 1,
      anon_sym_RPAREN,
  [1939] = 1,
    ACTIONS(304), 1,
      sym_string_content_dq,
  [1943] = 1,
    ACTIONS(306), 1,
      sym_string_content_sq,
  [1947] = 1,
    ACTIONS(308), 1,
      ts_builtin_sym_end,
  [1951] = 1,
    ACTIONS(276), 1,
      anon_sym_RBRACK,
  [1955] = 1,
    ACTIONS(310), 1,
      aux_sym__jinja_comment_token1,
  [1959] = 1,
    ACTIONS(312), 1,
      sym_string_content_sq,
  [1963] = 1,
    ACTIONS(314), 1,
      sym_string_content_dq,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 53,
  [SMALL_STATE(4)] = 106,
  [SMALL_STATE(5)] = 158,
  [SMALL_STATE(6)] = 208,
  [SMALL_STATE(7)] = 258,
  [SMALL_STATE(8)] = 308,
  [SMALL_STATE(9)] = 358,
  [SMALL_STATE(10)] = 410,
  [SMALL_STATE(11)] = 462,
  [SMALL_STATE(12)] = 514,
  [SMALL_STATE(13)] = 563,
  [SMALL_STATE(14)] = 612,
  [SMALL_STATE(15)] = 661,
  [SMALL_STATE(16)] = 710,
  [SMALL_STATE(17)] = 757,
  [SMALL_STATE(18)] = 806,
  [SMALL_STATE(19)] = 855,
  [SMALL_STATE(20)] = 904,
  [SMALL_STATE(21)] = 953,
  [SMALL_STATE(22)] = 999,
  [SMALL_STATE(23)] = 1045,
  [SMALL_STATE(24)] = 1091,
  [SMALL_STATE(25)] = 1137,
  [SMALL_STATE(26)] = 1166,
  [SMALL_STATE(27)] = 1195,
  [SMALL_STATE(28)] = 1220,
  [SMALL_STATE(29)] = 1245,
  [SMALL_STATE(30)] = 1267,
  [SMALL_STATE(31)] = 1289,
  [SMALL_STATE(32)] = 1311,
  [SMALL_STATE(33)] = 1333,
  [SMALL_STATE(34)] = 1352,
  [SMALL_STATE(35)] = 1362,
  [SMALL_STATE(36)] = 1372,
  [SMALL_STATE(37)] = 1382,
  [SMALL_STATE(38)] = 1390,
  [SMALL_STATE(39)] = 1400,
  [SMALL_STATE(40)] = 1410,
  [SMALL_STATE(41)] = 1420,
  [SMALL_STATE(42)] = 1427,
  [SMALL_STATE(43)] = 1434,
  [SMALL_STATE(44)] = 1441,
  [SMALL_STATE(45)] = 1448,
  [SMALL_STATE(46)] = 1455,
  [SMALL_STATE(47)] = 1462,
  [SMALL_STATE(48)] = 1469,
  [SMALL_STATE(49)] = 1476,
  [SMALL_STATE(50)] = 1483,
  [SMALL_STATE(51)] = 1490,
  [SMALL_STATE(52)] = 1497,
  [SMALL_STATE(53)] = 1504,
  [SMALL_STATE(54)] = 1511,
  [SMALL_STATE(55)] = 1518,
  [SMALL_STATE(56)] = 1525,
  [SMALL_STATE(57)] = 1536,
  [SMALL_STATE(58)] = 1543,
  [SMALL_STATE(59)] = 1550,
  [SMALL_STATE(60)] = 1560,
  [SMALL_STATE(61)] = 1570,
  [SMALL_STATE(62)] = 1576,
  [SMALL_STATE(63)] = 1586,
  [SMALL_STATE(64)] = 1596,
  [SMALL_STATE(65)] = 1606,
  [SMALL_STATE(66)] = 1616,
  [SMALL_STATE(67)] = 1626,
  [SMALL_STATE(68)] = 1636,
  [SMALL_STATE(69)] = 1646,
  [SMALL_STATE(70)] = 1656,
  [SMALL_STATE(71)] = 1666,
  [SMALL_STATE(72)] = 1676,
  [SMALL_STATE(73)] = 1686,
  [SMALL_STATE(74)] = 1696,
  [SMALL_STATE(75)] = 1706,
  [SMALL_STATE(76)] = 1716,
  [SMALL_STATE(77)] = 1726,
  [SMALL_STATE(78)] = 1736,
  [SMALL_STATE(79)] = 1746,
  [SMALL_STATE(80)] = 1751,
  [SMALL_STATE(81)] = 1756,
  [SMALL_STATE(82)] = 1761,
  [SMALL_STATE(83)] = 1766,
  [SMALL_STATE(84)] = 1771,
  [SMALL_STATE(85)] = 1776,
  [SMALL_STATE(86)] = 1781,
  [SMALL_STATE(87)] = 1786,
  [SMALL_STATE(88)] = 1791,
  [SMALL_STATE(89)] = 1796,
  [SMALL_STATE(90)] = 1801,
  [SMALL_STATE(91)] = 1806,
  [SMALL_STATE(92)] = 1811,
  [SMALL_STATE(93)] = 1818,
  [SMALL_STATE(94)] = 1823,
  [SMALL_STATE(95)] = 1828,
  [SMALL_STATE(96)] = 1833,
  [SMALL_STATE(97)] = 1838,
  [SMALL_STATE(98)] = 1843,
  [SMALL_STATE(99)] = 1848,
  [SMALL_STATE(100)] = 1853,
  [SMALL_STATE(101)] = 1858,
  [SMALL_STATE(102)] = 1865,
  [SMALL_STATE(103)] = 1870,
  [SMALL_STATE(104)] = 1875,
  [SMALL_STATE(105)] = 1879,
  [SMALL_STATE(106)] = 1883,
  [SMALL_STATE(107)] = 1887,
  [SMALL_STATE(108)] = 1891,
  [SMALL_STATE(109)] = 1895,
  [SMALL_STATE(110)] = 1899,
  [SMALL_STATE(111)] = 1903,
  [SMALL_STATE(112)] = 1907,
  [SMALL_STATE(113)] = 1911,
  [SMALL_STATE(114)] = 1915,
  [SMALL_STATE(115)] = 1919,
  [SMALL_STATE(116)] = 1923,
  [SMALL_STATE(117)] = 1927,
  [SMALL_STATE(118)] = 1931,
  [SMALL_STATE(119)] = 1935,
  [SMALL_STATE(120)] = 1939,
  [SMALL_STATE(121)] = 1943,
  [SMALL_STATE(122)] = 1947,
  [SMALL_STATE(123)] = 1951,
  [SMALL_STATE(124)] = 1955,
  [SMALL_STATE(125)] = 1959,
  [SMALL_STATE(126)] = 1963,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(118),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(124),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(100),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(102),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [69] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [85] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [105] = {.entry = {.count = 1, .reusable = false}}, SHIFT(115),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [109] = {.entry = {.count = 1, .reusable = false}}, SHIFT(99),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [119] = {.entry = {.count = 1, .reusable = false}}, SHIFT(103),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [125] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(22),
  [128] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(118),
  [131] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(124),
  [134] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(36),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jinja_expression, 2),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jinja_expression, 2),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 3),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 3),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text, 1),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_text, 1),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, .production_id = 2),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__jinja_comment, 2),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__jinja_comment, 2),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 1),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 1),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 1),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple, 2),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple, 3),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 5),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dict, 3),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn_call, 2, .production_id = 1),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple, 5),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dict, 5),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 2),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 3),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dict, 4),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 4),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 4),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dict, 2),
  [211] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2), SHIFT_REPEAT(21),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple, 4),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 5),
  [220] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_dict_repeat1, 2), SHIFT_REPEAT(33),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_dict_repeat1, 2),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [269] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2), SHIFT_REPEAT(16),
  [272] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [282] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pair, 3, .production_id = 3),
  [284] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [288] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_kwarg, 3, .production_id = 3),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [304] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_double_quote, 1),
  [306] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_single_quote, 1),
  [308] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_jinja2(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
