#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 129
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 50
#define ALIAS_COUNT 0
#define TOKEN_COUNT 26
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 6
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 4

enum {
  anon_sym_LBRACE_LBRACE = 1,
  anon_sym_RBRACE_RBRACE = 2,
  sym__single_quote = 3,
  sym__double_quote = 4,
  sym_string_content_sq = 5,
  sym_string_content_dq = 6,
  sym_integer = 7,
  sym_float = 8,
  anon_sym_LBRACK = 9,
  anon_sym_COMMA = 10,
  anon_sym_RBRACK = 11,
  anon_sym_LPAREN = 12,
  anon_sym_RPAREN = 13,
  anon_sym_LBRACE_PERCENT = 14,
  aux_sym_jinja_expression_token1 = 15,
  anon_sym_LBRACE_POUND = 16,
  aux_sym__jinja_comment_token1 = 17,
  anon_sym_True = 18,
  anon_sym_False = 19,
  anon_sym_LBRACE = 20,
  anon_sym_RBRACE = 21,
  anon_sym_COLON = 22,
  sym__identifier = 23,
  anon_sym_EQ = 24,
  sym__text = 25,
  sym_source_file = 26,
  sym_statement = 27,
  sym_expression = 28,
  sym_comment = 29,
  sym_text = 30,
  sym__expression = 31,
  sym_string = 32,
  sym_single_quote = 33,
  sym_double_quote = 34,
  sym_list = 35,
  sym_tuple = 36,
  sym_jinja_expression = 37,
  sym__jinja_comment = 38,
  sym_fn_call = 39,
  sym_argument_list = 40,
  sym_bool = 41,
  sym_dict = 42,
  sym_pair = 43,
  sym_identifier = 44,
  sym_kwarg = 45,
  aux_sym_source_file_repeat1 = 46,
  aux_sym_list_repeat1 = 47,
  aux_sym_argument_list_repeat1 = 48,
  aux_sym_dict_repeat1 = 49,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACE_LBRACE] = "{{",
  [anon_sym_RBRACE_RBRACE] = "}}",
  [sym__single_quote] = "_single_quote",
  [sym__double_quote] = "_double_quote",
  [sym_string_content_sq] = "string_content_sq",
  [sym_string_content_dq] = "string_content_dq",
  [sym_integer] = "integer",
  [sym_float] = "float",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACE_PERCENT] = "{%",
  [aux_sym_jinja_expression_token1] = "jinja_expression_token1",
  [anon_sym_LBRACE_POUND] = "{#",
  [aux_sym__jinja_comment_token1] = "_jinja_comment_token1",
  [anon_sym_True] = "True",
  [anon_sym_False] = "False",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COLON] = ":",
  [sym__identifier] = "_identifier",
  [anon_sym_EQ] = "=",
  [sym__text] = "_text",
  [sym_source_file] = "source_file",
  [sym_statement] = "statement",
  [sym_expression] = "expression",
  [sym_comment] = "comment",
  [sym_text] = "text",
  [sym__expression] = "_expression",
  [sym_string] = "string",
  [sym_single_quote] = "single_quote",
  [sym_double_quote] = "double_quote",
  [sym_list] = "list",
  [sym_tuple] = "tuple",
  [sym_jinja_expression] = "jinja_expression",
  [sym__jinja_comment] = "_jinja_comment",
  [sym_fn_call] = "fn_call",
  [sym_argument_list] = "argument_list",
  [sym_bool] = "bool",
  [sym_dict] = "dict",
  [sym_pair] = "pair",
  [sym_identifier] = "identifier",
  [sym_kwarg] = "kwarg",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_list_repeat1] = "list_repeat1",
  [aux_sym_argument_list_repeat1] = "argument_list_repeat1",
  [aux_sym_dict_repeat1] = "dict_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACE_LBRACE] = anon_sym_LBRACE_LBRACE,
  [anon_sym_RBRACE_RBRACE] = anon_sym_RBRACE_RBRACE,
  [sym__single_quote] = sym__single_quote,
  [sym__double_quote] = sym__double_quote,
  [sym_string_content_sq] = sym_string_content_sq,
  [sym_string_content_dq] = sym_string_content_dq,
  [sym_integer] = sym_integer,
  [sym_float] = sym_float,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACE_PERCENT] = anon_sym_LBRACE_PERCENT,
  [aux_sym_jinja_expression_token1] = aux_sym_jinja_expression_token1,
  [anon_sym_LBRACE_POUND] = anon_sym_LBRACE_POUND,
  [aux_sym__jinja_comment_token1] = aux_sym__jinja_comment_token1,
  [anon_sym_True] = anon_sym_True,
  [anon_sym_False] = anon_sym_False,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym__identifier] = sym__identifier,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym__text] = sym__text,
  [sym_source_file] = sym_source_file,
  [sym_statement] = sym_statement,
  [sym_expression] = sym_expression,
  [sym_comment] = sym_comment,
  [sym_text] = sym_text,
  [sym__expression] = sym__expression,
  [sym_string] = sym_string,
  [sym_single_quote] = sym_single_quote,
  [sym_double_quote] = sym_double_quote,
  [sym_list] = sym_list,
  [sym_tuple] = sym_tuple,
  [sym_jinja_expression] = sym_jinja_expression,
  [sym__jinja_comment] = sym__jinja_comment,
  [sym_fn_call] = sym_fn_call,
  [sym_argument_list] = sym_argument_list,
  [sym_bool] = sym_bool,
  [sym_dict] = sym_dict,
  [sym_pair] = sym_pair,
  [sym_identifier] = sym_identifier,
  [sym_kwarg] = sym_kwarg,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_list_repeat1] = aux_sym_list_repeat1,
  [aux_sym_argument_list_repeat1] = aux_sym_argument_list_repeat1,
  [aux_sym_dict_repeat1] = aux_sym_dict_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym__single_quote] = {
    .visible = false,
    .named = true,
  },
  [sym__double_quote] = {
    .visible = false,
    .named = true,
  },
  [sym_string_content_sq] = {
    .visible = true,
    .named = true,
  },
  [sym_string_content_dq] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_jinja_expression_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACE_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__jinja_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_True] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_False] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym__identifier] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym__text] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_single_quote] = {
    .visible = true,
    .named = true,
  },
  [sym_double_quote] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym_tuple] = {
    .visible = true,
    .named = true,
  },
  [sym_jinja_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__jinja_comment] = {
    .visible = false,
    .named = true,
  },
  [sym_fn_call] = {
    .visible = true,
    .named = true,
  },
  [sym_argument_list] = {
    .visible = true,
    .named = true,
  },
  [sym_bool] = {
    .visible = true,
    .named = true,
  },
  [sym_dict] = {
    .visible = true,
    .named = true,
  },
  [sym_pair] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_kwarg] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_argument_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_dict_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_argument_list = 1,
  field_fn_name = 2,
  field_key = 3,
  field_quote_type = 4,
  field_string_content = 5,
  field_value = 6,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_argument_list] = "argument_list",
  [field_fn_name] = "fn_name",
  [field_key] = "key",
  [field_quote_type] = "quote_type",
  [field_string_content] = "string_content",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 2},
  [3] = {.index = 4, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_argument_list, 1},
    {field_fn_name, 0},
  [2] =
    {field_quote_type, 0},
    {field_string_content, 1},
  [4] =
    {field_key, 0},
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 4,
  [8] = 6,
  [9] = 9,
  [10] = 5,
  [11] = 9,
  [12] = 12,
  [13] = 13,
  [14] = 12,
  [15] = 15,
  [16] = 16,
  [17] = 15,
  [18] = 13,
  [19] = 19,
  [20] = 16,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 27,
  [29] = 29,
  [30] = 30,
  [31] = 29,
  [32] = 30,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 62,
  [68] = 63,
  [69] = 69,
  [70] = 65,
  [71] = 69,
  [72] = 72,
  [73] = 72,
  [74] = 60,
  [75] = 61,
  [76] = 76,
  [77] = 77,
  [78] = 76,
  [79] = 79,
  [80] = 48,
  [81] = 81,
  [82] = 42,
  [83] = 41,
  [84] = 46,
  [85] = 49,
  [86] = 47,
  [87] = 44,
  [88] = 45,
  [89] = 39,
  [90] = 51,
  [91] = 54,
  [92] = 58,
  [93] = 55,
  [94] = 53,
  [95] = 95,
  [96] = 43,
  [97] = 56,
  [98] = 59,
  [99] = 52,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 102,
  [104] = 104,
  [105] = 50,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 106,
  [112] = 109,
  [113] = 113,
  [114] = 110,
  [115] = 115,
  [116] = 113,
  [117] = 117,
  [118] = 118,
  [119] = 117,
  [120] = 120,
  [121] = 108,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 115,
  [128] = 125,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(17);
      if (lookahead == '"') ADVANCE(21);
      if (lookahead == '\'') ADVANCE(20);
      if (lookahead == '(') ADVANCE(39);
      if (lookahead == ')') ADVANCE(40);
      if (lookahead == ',') ADVANCE(37);
      if (lookahead == '.') ADVANCE(13);
      if (lookahead == ':') ADVANCE(51);
      if (lookahead == '=') ADVANCE(60);
      if (lookahead == 'F') ADVANCE(52);
      if (lookahead == 'T') ADVANCE(56);
      if (lookahead == '[') ADVANCE(36);
      if (lookahead == ']') ADVANCE(38);
      if (lookahead == '{') ADVANCE(49);
      if (lookahead == '}') ADVANCE(50);
      if (('+' <= lookahead && lookahead <= '-')) ADVANCE(9);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(21);
      if (lookahead == '\'') ADVANCE(20);
      if (lookahead == '(') ADVANCE(39);
      if (lookahead == ')') ADVANCE(40);
      if (lookahead == ',') ADVANCE(37);
      if (lookahead == '.') ADVANCE(13);
      if (lookahead == ':') ADVANCE(51);
      if (lookahead == 'F') ADVANCE(52);
      if (lookahead == 'T') ADVANCE(56);
      if (lookahead == '[') ADVANCE(36);
      if (lookahead == ']') ADVANCE(38);
      if (lookahead == '{') ADVANCE(48);
      if (lookahead == '}') ADVANCE(10);
      if (('+' <= lookahead && lookahead <= '-')) ADVANCE(9);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 2:
      if (lookahead == '#') ADVANCE(43);
      if (lookahead == '%') ADVANCE(41);
      if (lookahead == '{') ADVANCE(18);
      if (lookahead != 0) ADVANCE(62);
      END_STATE();
    case 3:
      if (lookahead == '#') ADVANCE(6);
      if (lookahead == '}') ADVANCE(45);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 4:
      if (lookahead == '#') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(4);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '#') ADVANCE(6);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '#') ADVANCE(3);
      if (lookahead == '}') ADVANCE(44);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 7:
      if (lookahead == '%') ADVANCE(11);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(7);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 8:
      if (lookahead == '%') ADVANCE(11);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 9:
      if (lookahead == '.') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      END_STATE();
    case 10:
      if (lookahead == '}') ADVANCE(19);
      END_STATE();
    case 11:
      if (lookahead == '}') ADVANCE(42);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 12:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      END_STATE();
    case 13:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 14:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      END_STATE();
    case 15:
      if (lookahead != 0 &&
          lookahead != '#' &&
          lookahead != '%' &&
          lookahead != '{') ADVANCE(62);
      END_STATE();
    case 16:
      if (eof) ADVANCE(17);
      if (lookahead == '{') ADVANCE(2);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(61);
      if (lookahead != 0) ADVANCE(62);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym__single_quote);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym__double_quote);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_string_content_sq);
      if (lookahead == '\\') ADVANCE(24);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(23);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_string_content_sq);
      if (lookahead == '\\') ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_string_content_sq);
      if (lookahead != 0 &&
          lookahead != '\\') ADVANCE(23);
      if (lookahead == '\\') ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_string_content_dq);
      if (lookahead == '\\') ADVANCE(27);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(26);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_string_content_dq);
      if (lookahead == '\\') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_string_content_dq);
      if (lookahead != 0 &&
          lookahead != '\\') ADVANCE(26);
      if (lookahead == '\\') ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '.') ADVANCE(34);
      if (lookahead == '_') ADVANCE(30);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '.') ADVANCE(34);
      if (lookahead == '_') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '.') ADVANCE(34);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '.') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_float);
      if (lookahead == '_') ADVANCE(34);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_float);
      if (lookahead == '_') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_float);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_float);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_LBRACE_PERCENT);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_jinja_expression_token1);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_LBRACE_POUND);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym__jinja_comment_token1);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym__jinja_comment_token1);
      if (lookahead == '#') ADVANCE(6);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_True);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_False);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead == '#') ADVANCE(43);
      if (lookahead == '%') ADVANCE(41);
      if (lookahead == '{') ADVANCE(18);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead == 'a') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead == 'e') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead == 'e') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead == 'l') ADVANCE(57);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead == 'r') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead == 's') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead == 'u') ADVANCE(53);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym__identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym__text);
      if (lookahead == '{') ADVANCE(2);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(61);
      if (lookahead != 0) ADVANCE(62);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym__text);
      if (lookahead == '{') ADVANCE(15);
      if (lookahead != 0) ADVANCE(62);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 16},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 16},
  [26] = {.lex_state = 16},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 16},
  [35] = {.lex_state = 16},
  [36] = {.lex_state = 16},
  [37] = {.lex_state = 16},
  [38] = {.lex_state = 16},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 16},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 1},
  [59] = {.lex_state = 1},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 22},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 25},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 22},
  [116] = {.lex_state = 25},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 7},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 25},
  [123] = {.lex_state = 1},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 4},
  [127] = {.lex_state = 22},
  [128] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(1),
    [sym__single_quote] = ACTIONS(1),
    [sym__double_quote] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [sym_float] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACE_PERCENT] = ACTIONS(1),
    [anon_sym_LBRACE_POUND] = ACTIONS(1),
    [anon_sym_True] = ACTIONS(1),
    [anon_sym_False] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym__identifier] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(124),
    [sym_statement] = STATE(26),
    [sym_expression] = STATE(26),
    [sym_comment] = STATE(26),
    [sym_text] = STATE(26),
    [sym_jinja_expression] = STATE(35),
    [sym__jinja_comment] = STATE(38),
    [aux_sym_source_file_repeat1] = STATE(26),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(5),
    [anon_sym_LBRACE_PERCENT] = ACTIONS(7),
    [anon_sym_LBRACE_POUND] = ACTIONS(9),
    [sym__text] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 15,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(17), 1,
      sym_integer,
    ACTIONS(19), 1,
      sym_float,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_COMMA,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      anon_sym_RPAREN,
    ACTIONS(31), 1,
      anon_sym_LBRACE,
    ACTIONS(33), 1,
      sym__identifier,
    STATE(66), 1,
      sym_identifier,
    STATE(113), 1,
      sym_double_quote,
    STATE(115), 1,
      sym_single_quote,
    ACTIONS(29), 2,
      anon_sym_True,
      anon_sym_False,
    STATE(68), 8,
      sym__expression,
      sym_string,
      sym_list,
      sym_tuple,
      sym_fn_call,
      sym_bool,
      sym_dict,
      sym_kwarg,
  [54] = 15,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_LBRACE,
    ACTIONS(33), 1,
      sym__identifier,
    ACTIONS(35), 1,
      sym_integer,
    ACTIONS(37), 1,
      sym_float,
    ACTIONS(39), 1,
      anon_sym_COMMA,
    ACTIONS(41), 1,
      anon_sym_RPAREN,
    STATE(66), 1,
      sym_identifier,
    STATE(113), 1,
      sym_double_quote,
    STATE(115), 1,
      sym_single_quote,
    ACTIONS(29), 2,
      anon_sym_True,
      anon_sym_False,
    STATE(63), 8,
      sym__expression,
      sym_string,
      sym_list,
      sym_tuple,
      sym_fn_call,
      sym_bool,
      sym_dict,
      sym_kwarg,
  [108] = 15,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_LBRACE,
    ACTIONS(33), 1,
      sym__identifier,
    ACTIONS(43), 1,
      sym_integer,
    ACTIONS(45), 1,
      sym_float,
    ACTIONS(47), 1,
      anon_sym_COMMA,
    ACTIONS(49), 1,
      anon_sym_RBRACK,
    STATE(102), 1,
      sym_identifier,
    STATE(113), 1,
      sym_double_quote,
    STATE(115), 1,
      sym_single_quote,
    ACTIONS(29), 2,
      anon_sym_True,
      anon_sym_False,
    STATE(78), 7,
      sym__expression,
      sym_string,
      sym_list,
      sym_tuple,
      sym_fn_call,
      sym_bool,
      sym_dict,
  [161] = 14,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_LBRACE,
    ACTIONS(33), 1,
      sym__identifier,
    ACTIONS(51), 1,
      sym_integer,
    ACTIONS(53), 1,
      sym_float,
    ACTIONS(55), 1,
      anon_sym_RPAREN,
    STATE(66), 1,
      sym_identifier,
    STATE(113), 1,
      sym_double_quote,
    STATE(115), 1,
      sym_single_quote,
    ACTIONS(29), 2,
      anon_sym_True,
      anon_sym_False,
    STATE(104), 8,
      sym__expression,
      sym_string,
      sym_list,
      sym_tuple,
      sym_fn_call,
      sym_bool,
      sym_dict,
      sym_kwarg,
  [212] = 14,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_LBRACE,
    ACTIONS(33), 1,
      sym__identifier,
    ACTIONS(51), 1,
      sym_integer,
    ACTIONS(53), 1,
      sym_float,
    ACTIONS(57), 1,
      anon_sym_RPAREN,
    STATE(66), 1,
      sym_identifier,
    STATE(113), 1,
      sym_double_quote,
    STATE(115), 1,
      sym_single_quote,
    ACTIONS(29), 2,
      anon_sym_True,
      anon_sym_False,
    STATE(104), 8,
      sym__expression,
      sym_string,
      sym_list,
      sym_tuple,
      sym_fn_call,
      sym_bool,
      sym_dict,
      sym_kwarg,
  [263] = 15,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_LBRACE,
    ACTIONS(33), 1,
      sym__identifier,
    ACTIONS(59), 1,
      sym_integer,
    ACTIONS(61), 1,
      sym_float,
    ACTIONS(63), 1,
      anon_sym_COMMA,
    ACTIONS(65), 1,
      anon_sym_RBRACK,
    STATE(102), 1,
      sym_identifier,
    STATE(113), 1,
      sym_double_quote,
    STATE(115), 1,
      sym_single_quote,
    ACTIONS(29), 2,
      anon_sym_True,
      anon_sym_False,
    STATE(76), 7,
      sym__expression,
      sym_string,
      sym_list,
      sym_tuple,
      sym_fn_call,
      sym_bool,
      sym_dict,
  [316] = 14,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_LBRACE,
    ACTIONS(33), 1,
      sym__identifier,
    ACTIONS(51), 1,
      sym_integer,
    ACTIONS(53), 1,
      sym_float,
    ACTIONS(67), 1,
      anon_sym_RPAREN,
    STATE(66), 1,
      sym_identifier,
    STATE(113), 1,
      sym_double_quote,
    STATE(115), 1,
      sym_single_quote,
    ACTIONS(29), 2,
      anon_sym_True,
      anon_sym_False,
    STATE(104), 8,
      sym__expression,
      sym_string,
      sym_list,
      sym_tuple,
      sym_fn_call,
      sym_bool,
      sym_dict,
      sym_kwarg,
  [367] = 15,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_LBRACE,
    ACTIONS(33), 1,
      sym__identifier,
    ACTIONS(69), 1,
      sym_integer,
    ACTIONS(71), 1,
      sym_float,
    ACTIONS(73), 1,
      anon_sym_COMMA,
    ACTIONS(75), 1,
      anon_sym_RPAREN,
    STATE(102), 1,
      sym_identifier,
    STATE(113), 1,
      sym_double_quote,
    STATE(115), 1,
      sym_single_quote,
    ACTIONS(29), 2,
      anon_sym_True,
      anon_sym_False,
    STATE(75), 7,
      sym__expression,
      sym_string,
      sym_list,
      sym_tuple,
      sym_fn_call,
      sym_bool,
      sym_dict,
  [420] = 14,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_LBRACE,
    ACTIONS(33), 1,
      sym__identifier,
    ACTIONS(51), 1,
      sym_integer,
    ACTIONS(53), 1,
      sym_float,
    ACTIONS(77), 1,
      anon_sym_RPAREN,
    STATE(66), 1,
      sym_identifier,
    STATE(113), 1,
      sym_double_quote,
    STATE(115), 1,
      sym_single_quote,
    ACTIONS(29), 2,
      anon_sym_True,
      anon_sym_False,
    STATE(104), 8,
      sym__expression,
      sym_string,
      sym_list,
      sym_tuple,
      sym_fn_call,
      sym_bool,
      sym_dict,
      sym_kwarg,
  [471] = 15,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_LBRACE,
    ACTIONS(33), 1,
      sym__identifier,
    ACTIONS(79), 1,
      sym_integer,
    ACTIONS(81), 1,
      sym_float,
    ACTIONS(83), 1,
      anon_sym_COMMA,
    ACTIONS(85), 1,
      anon_sym_RPAREN,
    STATE(102), 1,
      sym_identifier,
    STATE(113), 1,
      sym_double_quote,
    STATE(115), 1,
      sym_single_quote,
    ACTIONS(29), 2,
      anon_sym_True,
      anon_sym_False,
    STATE(61), 7,
      sym__expression,
      sym_string,
      sym_list,
      sym_tuple,
      sym_fn_call,
      sym_bool,
      sym_dict,
  [524] = 14,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_LBRACE,
    ACTIONS(33), 1,
      sym__identifier,
    ACTIONS(87), 1,
      sym_integer,
    ACTIONS(89), 1,
      sym_float,
    ACTIONS(91), 1,
      anon_sym_RPAREN,
    STATE(102), 1,
      sym_identifier,
    STATE(113), 1,
      sym_double_quote,
    STATE(115), 1,
      sym_single_quote,
    ACTIONS(29), 2,
      anon_sym_True,
      anon_sym_False,
    STATE(79), 7,
      sym__expression,
      sym_string,
      sym_list,
      sym_tuple,
      sym_fn_call,
      sym_bool,
      sym_dict,
  [574] = 14,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_LBRACE,
    ACTIONS(33), 1,
      sym__identifier,
    ACTIONS(87), 1,
      sym_integer,
    ACTIONS(89), 1,
      sym_float,
    ACTIONS(93), 1,
      anon_sym_RBRACK,
    STATE(102), 1,
      sym_identifier,
    STATE(113), 1,
      sym_double_quote,
    STATE(115), 1,
      sym_single_quote,
    ACTIONS(29), 2,
      anon_sym_True,
      anon_sym_False,
    STATE(79), 7,
      sym__expression,
      sym_string,
      sym_list,
      sym_tuple,
      sym_fn_call,
      sym_bool,
      sym_dict,
  [624] = 14,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_LBRACE,
    ACTIONS(33), 1,
      sym__identifier,
    ACTIONS(87), 1,
      sym_integer,
    ACTIONS(89), 1,
      sym_float,
    ACTIONS(95), 1,
      anon_sym_RPAREN,
    STATE(102), 1,
      sym_identifier,
    STATE(113), 1,
      sym_double_quote,
    STATE(115), 1,
      sym_single_quote,
    ACTIONS(29), 2,
      anon_sym_True,
      anon_sym_False,
    STATE(79), 7,
      sym__expression,
      sym_string,
      sym_list,
      sym_tuple,
      sym_fn_call,
      sym_bool,
      sym_dict,
  [674] = 14,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_LBRACE,
    ACTIONS(33), 1,
      sym__identifier,
    ACTIONS(87), 1,
      sym_integer,
    ACTIONS(89), 1,
      sym_float,
    ACTIONS(97), 1,
      anon_sym_RBRACK,
    STATE(102), 1,
      sym_identifier,
    STATE(113), 1,
      sym_double_quote,
    STATE(115), 1,
      sym_single_quote,
    ACTIONS(29), 2,
      anon_sym_True,
      anon_sym_False,
    STATE(79), 7,
      sym__expression,
      sym_string,
      sym_list,
      sym_tuple,
      sym_fn_call,
      sym_bool,
      sym_dict,
  [724] = 14,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_LBRACE,
    ACTIONS(33), 1,
      sym__identifier,
    ACTIONS(87), 1,
      sym_integer,
    ACTIONS(89), 1,
      sym_float,
    ACTIONS(99), 1,
      anon_sym_RPAREN,
    STATE(102), 1,
      sym_identifier,
    STATE(113), 1,
      sym_double_quote,
    STATE(115), 1,
      sym_single_quote,
    ACTIONS(29), 2,
      anon_sym_True,
      anon_sym_False,
    STATE(79), 7,
      sym__expression,
      sym_string,
      sym_list,
      sym_tuple,
      sym_fn_call,
      sym_bool,
      sym_dict,
  [774] = 14,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_LBRACE,
    ACTIONS(33), 1,
      sym__identifier,
    ACTIONS(87), 1,
      sym_integer,
    ACTIONS(89), 1,
      sym_float,
    ACTIONS(101), 1,
      anon_sym_RBRACK,
    STATE(102), 1,
      sym_identifier,
    STATE(113), 1,
      sym_double_quote,
    STATE(115), 1,
      sym_single_quote,
    ACTIONS(29), 2,
      anon_sym_True,
      anon_sym_False,
    STATE(79), 7,
      sym__expression,
      sym_string,
      sym_list,
      sym_tuple,
      sym_fn_call,
      sym_bool,
      sym_dict,
  [824] = 14,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_LBRACE,
    ACTIONS(33), 1,
      sym__identifier,
    ACTIONS(87), 1,
      sym_integer,
    ACTIONS(89), 1,
      sym_float,
    ACTIONS(103), 1,
      anon_sym_RBRACK,
    STATE(102), 1,
      sym_identifier,
    STATE(113), 1,
      sym_double_quote,
    STATE(115), 1,
      sym_single_quote,
    ACTIONS(29), 2,
      anon_sym_True,
      anon_sym_False,
    STATE(79), 7,
      sym__expression,
      sym_string,
      sym_list,
      sym_tuple,
      sym_fn_call,
      sym_bool,
      sym_dict,
  [874] = 13,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_LBRACE,
    ACTIONS(33), 1,
      sym__identifier,
    ACTIONS(51), 1,
      sym_integer,
    ACTIONS(53), 1,
      sym_float,
    STATE(66), 1,
      sym_identifier,
    STATE(113), 1,
      sym_double_quote,
    STATE(115), 1,
      sym_single_quote,
    ACTIONS(29), 2,
      anon_sym_True,
      anon_sym_False,
    STATE(104), 8,
      sym__expression,
      sym_string,
      sym_list,
      sym_tuple,
      sym_fn_call,
      sym_bool,
      sym_dict,
      sym_kwarg,
  [922] = 14,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_LBRACE,
    ACTIONS(33), 1,
      sym__identifier,
    ACTIONS(87), 1,
      sym_integer,
    ACTIONS(89), 1,
      sym_float,
    ACTIONS(105), 1,
      anon_sym_RPAREN,
    STATE(102), 1,
      sym_identifier,
    STATE(113), 1,
      sym_double_quote,
    STATE(115), 1,
      sym_single_quote,
    ACTIONS(29), 2,
      anon_sym_True,
      anon_sym_False,
    STATE(79), 7,
      sym__expression,
      sym_string,
      sym_list,
      sym_tuple,
      sym_fn_call,
      sym_bool,
      sym_dict,
  [972] = 13,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(33), 1,
      sym__identifier,
    ACTIONS(107), 1,
      sym_integer,
    ACTIONS(109), 1,
      sym_float,
    ACTIONS(111), 1,
      anon_sym_LBRACK,
    ACTIONS(113), 1,
      anon_sym_LPAREN,
    ACTIONS(117), 1,
      anon_sym_LBRACE,
    STATE(103), 1,
      sym_identifier,
    STATE(116), 1,
      sym_double_quote,
    STATE(127), 1,
      sym_single_quote,
    ACTIONS(115), 2,
      anon_sym_True,
      anon_sym_False,
    STATE(95), 7,
      sym__expression,
      sym_string,
      sym_list,
      sym_tuple,
      sym_fn_call,
      sym_bool,
      sym_dict,
  [1019] = 13,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_LBRACE,
    ACTIONS(33), 1,
      sym__identifier,
    ACTIONS(87), 1,
      sym_integer,
    ACTIONS(89), 1,
      sym_float,
    STATE(102), 1,
      sym_identifier,
    STATE(113), 1,
      sym_double_quote,
    STATE(115), 1,
      sym_single_quote,
    ACTIONS(29), 2,
      anon_sym_True,
      anon_sym_False,
    STATE(79), 7,
      sym__expression,
      sym_string,
      sym_list,
      sym_tuple,
      sym_fn_call,
      sym_bool,
      sym_dict,
  [1066] = 13,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_LBRACE,
    ACTIONS(33), 1,
      sym__identifier,
    ACTIONS(119), 1,
      sym_integer,
    ACTIONS(121), 1,
      sym_float,
    STATE(102), 1,
      sym_identifier,
    STATE(113), 1,
      sym_double_quote,
    STATE(115), 1,
      sym_single_quote,
    ACTIONS(29), 2,
      anon_sym_True,
      anon_sym_False,
    STATE(123), 7,
      sym__expression,
      sym_string,
      sym_list,
      sym_tuple,
      sym_fn_call,
      sym_bool,
      sym_dict,
  [1113] = 13,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_LBRACE,
    ACTIONS(33), 1,
      sym__identifier,
    ACTIONS(123), 1,
      sym_integer,
    ACTIONS(125), 1,
      sym_float,
    STATE(102), 1,
      sym_identifier,
    STATE(113), 1,
      sym_double_quote,
    STATE(115), 1,
      sym_single_quote,
    ACTIONS(29), 2,
      anon_sym_True,
      anon_sym_False,
    STATE(81), 7,
      sym__expression,
      sym_string,
      sym_list,
      sym_tuple,
      sym_fn_call,
      sym_bool,
      sym_dict,
  [1160] = 8,
    ACTIONS(127), 1,
      ts_builtin_sym_end,
    ACTIONS(129), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(132), 1,
      anon_sym_LBRACE_PERCENT,
    ACTIONS(135), 1,
      anon_sym_LBRACE_POUND,
    ACTIONS(138), 1,
      sym__text,
    STATE(35), 1,
      sym_jinja_expression,
    STATE(38), 1,
      sym__jinja_comment,
    STATE(25), 5,
      sym_statement,
      sym_expression,
      sym_comment,
      sym_text,
      aux_sym_source_file_repeat1,
  [1189] = 8,
    ACTIONS(5), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(7), 1,
      anon_sym_LBRACE_PERCENT,
    ACTIONS(9), 1,
      anon_sym_LBRACE_POUND,
    ACTIONS(11), 1,
      sym__text,
    ACTIONS(141), 1,
      ts_builtin_sym_end,
    STATE(35), 1,
      sym_jinja_expression,
    STATE(38), 1,
      sym__jinja_comment,
    STATE(25), 5,
      sym_statement,
      sym_expression,
      sym_comment,
      sym_text,
      aux_sym_source_file_repeat1,
  [1218] = 8,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(143), 1,
      anon_sym_COMMA,
    ACTIONS(145), 1,
      anon_sym_RBRACE,
    STATE(60), 1,
      sym_pair,
    STATE(113), 1,
      sym_double_quote,
    STATE(115), 1,
      sym_single_quote,
    STATE(118), 1,
      sym_string,
  [1243] = 8,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(147), 1,
      anon_sym_COMMA,
    ACTIONS(149), 1,
      anon_sym_RBRACE,
    STATE(74), 1,
      sym_pair,
    STATE(113), 1,
      sym_double_quote,
    STATE(115), 1,
      sym_single_quote,
    STATE(118), 1,
      sym_string,
  [1268] = 7,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(151), 1,
      anon_sym_RBRACE,
    STATE(100), 1,
      sym_pair,
    STATE(113), 1,
      sym_double_quote,
    STATE(115), 1,
      sym_single_quote,
    STATE(118), 1,
      sym_string,
  [1290] = 7,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(153), 1,
      anon_sym_RBRACE,
    STATE(100), 1,
      sym_pair,
    STATE(113), 1,
      sym_double_quote,
    STATE(115), 1,
      sym_single_quote,
    STATE(118), 1,
      sym_string,
  [1312] = 7,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(155), 1,
      anon_sym_RBRACE,
    STATE(100), 1,
      sym_pair,
    STATE(113), 1,
      sym_double_quote,
    STATE(115), 1,
      sym_single_quote,
    STATE(118), 1,
      sym_string,
  [1334] = 7,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    ACTIONS(157), 1,
      anon_sym_RBRACE,
    STATE(100), 1,
      sym_pair,
    STATE(113), 1,
      sym_double_quote,
    STATE(115), 1,
      sym_single_quote,
    STATE(118), 1,
      sym_string,
  [1356] = 6,
    ACTIONS(13), 1,
      sym__single_quote,
    ACTIONS(15), 1,
      sym__double_quote,
    STATE(100), 1,
      sym_pair,
    STATE(113), 1,
      sym_double_quote,
    STATE(115), 1,
      sym_single_quote,
    STATE(118), 1,
      sym_string,
  [1375] = 2,
    ACTIONS(159), 2,
      ts_builtin_sym_end,
      sym__text,
    ACTIONS(161), 3,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_POUND,
  [1385] = 2,
    ACTIONS(163), 2,
      ts_builtin_sym_end,
      sym__text,
    ACTIONS(165), 3,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_POUND,
  [1395] = 2,
    ACTIONS(167), 2,
      ts_builtin_sym_end,
      sym__text,
    ACTIONS(169), 3,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_POUND,
  [1405] = 2,
    ACTIONS(171), 2,
      ts_builtin_sym_end,
      sym__text,
    ACTIONS(173), 3,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_POUND,
  [1415] = 2,
    ACTIONS(175), 2,
      ts_builtin_sym_end,
      sym__text,
    ACTIONS(177), 3,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_POUND,
  [1425] = 1,
    ACTIONS(179), 5,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_COLON,
  [1433] = 2,
    ACTIONS(181), 2,
      ts_builtin_sym_end,
      sym__text,
    ACTIONS(183), 3,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_POUND,
  [1443] = 1,
    ACTIONS(185), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1450] = 1,
    ACTIONS(187), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1457] = 1,
    ACTIONS(189), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1464] = 1,
    ACTIONS(191), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1471] = 1,
    ACTIONS(193), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1478] = 1,
    ACTIONS(195), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1485] = 1,
    ACTIONS(197), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1492] = 1,
    ACTIONS(199), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1499] = 1,
    ACTIONS(201), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1506] = 1,
    ACTIONS(203), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1513] = 1,
    ACTIONS(205), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1520] = 1,
    ACTIONS(207), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1527] = 1,
    ACTIONS(209), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1534] = 1,
    ACTIONS(211), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1541] = 1,
    ACTIONS(213), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1548] = 1,
    ACTIONS(215), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1555] = 3,
    ACTIONS(217), 1,
      anon_sym_COMMA,
    STATE(57), 1,
      aux_sym_list_repeat1,
    ACTIONS(220), 2,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1566] = 1,
    ACTIONS(222), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1573] = 1,
    ACTIONS(224), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1580] = 3,
    ACTIONS(226), 1,
      anon_sym_COMMA,
    ACTIONS(228), 1,
      anon_sym_RBRACE,
    STATE(70), 1,
      aux_sym_dict_repeat1,
  [1590] = 3,
    ACTIONS(230), 1,
      anon_sym_COMMA,
    ACTIONS(232), 1,
      anon_sym_RPAREN,
    STATE(71), 1,
      aux_sym_list_repeat1,
  [1600] = 3,
    ACTIONS(57), 1,
      anon_sym_RPAREN,
    ACTIONS(234), 1,
      anon_sym_COMMA,
    STATE(77), 1,
      aux_sym_argument_list_repeat1,
  [1610] = 3,
    ACTIONS(236), 1,
      anon_sym_COMMA,
    ACTIONS(238), 1,
      anon_sym_RPAREN,
    STATE(62), 1,
      aux_sym_argument_list_repeat1,
  [1620] = 3,
    ACTIONS(240), 1,
      anon_sym_COMMA,
    ACTIONS(243), 1,
      anon_sym_RBRACE,
    STATE(64), 1,
      aux_sym_dict_repeat1,
  [1630] = 3,
    ACTIONS(151), 1,
      anon_sym_RBRACE,
    ACTIONS(245), 1,
      anon_sym_COMMA,
    STATE(64), 1,
      aux_sym_dict_repeat1,
  [1640] = 3,
    ACTIONS(247), 1,
      anon_sym_LPAREN,
    ACTIONS(249), 1,
      anon_sym_EQ,
    STATE(49), 1,
      sym_argument_list,
  [1650] = 3,
    ACTIONS(67), 1,
      anon_sym_RPAREN,
    ACTIONS(251), 1,
      anon_sym_COMMA,
    STATE(77), 1,
      aux_sym_argument_list_repeat1,
  [1660] = 3,
    ACTIONS(253), 1,
      anon_sym_COMMA,
    ACTIONS(255), 1,
      anon_sym_RPAREN,
    STATE(67), 1,
      aux_sym_argument_list_repeat1,
  [1670] = 3,
    ACTIONS(95), 1,
      anon_sym_RPAREN,
    ACTIONS(257), 1,
      anon_sym_COMMA,
    STATE(57), 1,
      aux_sym_list_repeat1,
  [1680] = 3,
    ACTIONS(155), 1,
      anon_sym_RBRACE,
    ACTIONS(259), 1,
      anon_sym_COMMA,
    STATE(64), 1,
      aux_sym_dict_repeat1,
  [1690] = 3,
    ACTIONS(91), 1,
      anon_sym_RPAREN,
    ACTIONS(261), 1,
      anon_sym_COMMA,
    STATE(57), 1,
      aux_sym_list_repeat1,
  [1700] = 3,
    ACTIONS(101), 1,
      anon_sym_RBRACK,
    ACTIONS(263), 1,
      anon_sym_COMMA,
    STATE(57), 1,
      aux_sym_list_repeat1,
  [1710] = 3,
    ACTIONS(97), 1,
      anon_sym_RBRACK,
    ACTIONS(265), 1,
      anon_sym_COMMA,
    STATE(57), 1,
      aux_sym_list_repeat1,
  [1720] = 3,
    ACTIONS(267), 1,
      anon_sym_COMMA,
    ACTIONS(269), 1,
      anon_sym_RBRACE,
    STATE(65), 1,
      aux_sym_dict_repeat1,
  [1730] = 3,
    ACTIONS(271), 1,
      anon_sym_COMMA,
    ACTIONS(273), 1,
      anon_sym_RPAREN,
    STATE(69), 1,
      aux_sym_list_repeat1,
  [1740] = 3,
    ACTIONS(275), 1,
      anon_sym_COMMA,
    ACTIONS(277), 1,
      anon_sym_RBRACK,
    STATE(73), 1,
      aux_sym_list_repeat1,
  [1750] = 3,
    ACTIONS(279), 1,
      anon_sym_COMMA,
    ACTIONS(282), 1,
      anon_sym_RPAREN,
    STATE(77), 1,
      aux_sym_argument_list_repeat1,
  [1760] = 3,
    ACTIONS(284), 1,
      anon_sym_COMMA,
    ACTIONS(286), 1,
      anon_sym_RBRACK,
    STATE(72), 1,
      aux_sym_list_repeat1,
  [1770] = 1,
    ACTIONS(220), 3,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1776] = 1,
    ACTIONS(199), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1781] = 1,
    ACTIONS(288), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1786] = 1,
    ACTIONS(187), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1791] = 1,
    ACTIONS(185), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1796] = 1,
    ACTIONS(195), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1801] = 1,
    ACTIONS(201), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1806] = 1,
    ACTIONS(197), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1811] = 1,
    ACTIONS(191), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1816] = 1,
    ACTIONS(193), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1821] = 1,
    ACTIONS(179), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1826] = 1,
    ACTIONS(205), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1831] = 1,
    ACTIONS(211), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1836] = 1,
    ACTIONS(222), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1841] = 1,
    ACTIONS(213), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1846] = 1,
    ACTIONS(209), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1851] = 1,
    ACTIONS(290), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1856] = 1,
    ACTIONS(189), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1861] = 1,
    ACTIONS(215), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1866] = 1,
    ACTIONS(224), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1871] = 1,
    ACTIONS(207), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1876] = 1,
    ACTIONS(243), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1881] = 1,
    ACTIONS(292), 2,
      anon_sym_LPAREN,
      anon_sym_EQ,
  [1886] = 2,
    ACTIONS(247), 1,
      anon_sym_LPAREN,
    STATE(49), 1,
      sym_argument_list,
  [1893] = 2,
    ACTIONS(294), 1,
      anon_sym_LPAREN,
    STATE(85), 1,
      sym_argument_list,
  [1900] = 1,
    ACTIONS(282), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1905] = 1,
    ACTIONS(203), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1910] = 1,
    ACTIONS(296), 1,
      sym__double_quote,
  [1914] = 1,
    ACTIONS(298), 1,
      sym_string_content_sq,
  [1918] = 1,
    ACTIONS(269), 1,
      anon_sym_RBRACE,
  [1922] = 1,
    ACTIONS(277), 1,
      anon_sym_RBRACK,
  [1926] = 1,
    ACTIONS(300), 1,
      sym__single_quote,
  [1930] = 1,
    ACTIONS(300), 1,
      sym__double_quote,
  [1934] = 1,
    ACTIONS(286), 1,
      anon_sym_RBRACK,
  [1938] = 1,
    ACTIONS(302), 1,
      sym_string_content_dq,
  [1942] = 1,
    ACTIONS(296), 1,
      sym__single_quote,
  [1946] = 1,
    ACTIONS(304), 1,
      sym_string_content_sq,
  [1950] = 1,
    ACTIONS(306), 1,
      sym_string_content_dq,
  [1954] = 1,
    ACTIONS(255), 1,
      anon_sym_RPAREN,
  [1958] = 1,
    ACTIONS(308), 1,
      anon_sym_COLON,
  [1962] = 1,
    ACTIONS(238), 1,
      anon_sym_RPAREN,
  [1966] = 1,
    ACTIONS(310), 1,
      aux_sym_jinja_expression_token1,
  [1970] = 1,
    ACTIONS(228), 1,
      anon_sym_RBRACE,
  [1974] = 1,
    ACTIONS(312), 1,
      sym_string_content_dq,
  [1978] = 1,
    ACTIONS(314), 1,
      anon_sym_RBRACE_RBRACE,
  [1982] = 1,
    ACTIONS(316), 1,
      ts_builtin_sym_end,
  [1986] = 1,
    ACTIONS(232), 1,
      anon_sym_RPAREN,
  [1990] = 1,
    ACTIONS(318), 1,
      aux_sym__jinja_comment_token1,
  [1994] = 1,
    ACTIONS(320), 1,
      sym_string_content_sq,
  [1998] = 1,
    ACTIONS(273), 1,
      anon_sym_RPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 54,
  [SMALL_STATE(4)] = 108,
  [SMALL_STATE(5)] = 161,
  [SMALL_STATE(6)] = 212,
  [SMALL_STATE(7)] = 263,
  [SMALL_STATE(8)] = 316,
  [SMALL_STATE(9)] = 367,
  [SMALL_STATE(10)] = 420,
  [SMALL_STATE(11)] = 471,
  [SMALL_STATE(12)] = 524,
  [SMALL_STATE(13)] = 574,
  [SMALL_STATE(14)] = 624,
  [SMALL_STATE(15)] = 674,
  [SMALL_STATE(16)] = 724,
  [SMALL_STATE(17)] = 774,
  [SMALL_STATE(18)] = 824,
  [SMALL_STATE(19)] = 874,
  [SMALL_STATE(20)] = 922,
  [SMALL_STATE(21)] = 972,
  [SMALL_STATE(22)] = 1019,
  [SMALL_STATE(23)] = 1066,
  [SMALL_STATE(24)] = 1113,
  [SMALL_STATE(25)] = 1160,
  [SMALL_STATE(26)] = 1189,
  [SMALL_STATE(27)] = 1218,
  [SMALL_STATE(28)] = 1243,
  [SMALL_STATE(29)] = 1268,
  [SMALL_STATE(30)] = 1290,
  [SMALL_STATE(31)] = 1312,
  [SMALL_STATE(32)] = 1334,
  [SMALL_STATE(33)] = 1356,
  [SMALL_STATE(34)] = 1375,
  [SMALL_STATE(35)] = 1385,
  [SMALL_STATE(36)] = 1395,
  [SMALL_STATE(37)] = 1405,
  [SMALL_STATE(38)] = 1415,
  [SMALL_STATE(39)] = 1425,
  [SMALL_STATE(40)] = 1433,
  [SMALL_STATE(41)] = 1443,
  [SMALL_STATE(42)] = 1450,
  [SMALL_STATE(43)] = 1457,
  [SMALL_STATE(44)] = 1464,
  [SMALL_STATE(45)] = 1471,
  [SMALL_STATE(46)] = 1478,
  [SMALL_STATE(47)] = 1485,
  [SMALL_STATE(48)] = 1492,
  [SMALL_STATE(49)] = 1499,
  [SMALL_STATE(50)] = 1506,
  [SMALL_STATE(51)] = 1513,
  [SMALL_STATE(52)] = 1520,
  [SMALL_STATE(53)] = 1527,
  [SMALL_STATE(54)] = 1534,
  [SMALL_STATE(55)] = 1541,
  [SMALL_STATE(56)] = 1548,
  [SMALL_STATE(57)] = 1555,
  [SMALL_STATE(58)] = 1566,
  [SMALL_STATE(59)] = 1573,
  [SMALL_STATE(60)] = 1580,
  [SMALL_STATE(61)] = 1590,
  [SMALL_STATE(62)] = 1600,
  [SMALL_STATE(63)] = 1610,
  [SMALL_STATE(64)] = 1620,
  [SMALL_STATE(65)] = 1630,
  [SMALL_STATE(66)] = 1640,
  [SMALL_STATE(67)] = 1650,
  [SMALL_STATE(68)] = 1660,
  [SMALL_STATE(69)] = 1670,
  [SMALL_STATE(70)] = 1680,
  [SMALL_STATE(71)] = 1690,
  [SMALL_STATE(72)] = 1700,
  [SMALL_STATE(73)] = 1710,
  [SMALL_STATE(74)] = 1720,
  [SMALL_STATE(75)] = 1730,
  [SMALL_STATE(76)] = 1740,
  [SMALL_STATE(77)] = 1750,
  [SMALL_STATE(78)] = 1760,
  [SMALL_STATE(79)] = 1770,
  [SMALL_STATE(80)] = 1776,
  [SMALL_STATE(81)] = 1781,
  [SMALL_STATE(82)] = 1786,
  [SMALL_STATE(83)] = 1791,
  [SMALL_STATE(84)] = 1796,
  [SMALL_STATE(85)] = 1801,
  [SMALL_STATE(86)] = 1806,
  [SMALL_STATE(87)] = 1811,
  [SMALL_STATE(88)] = 1816,
  [SMALL_STATE(89)] = 1821,
  [SMALL_STATE(90)] = 1826,
  [SMALL_STATE(91)] = 1831,
  [SMALL_STATE(92)] = 1836,
  [SMALL_STATE(93)] = 1841,
  [SMALL_STATE(94)] = 1846,
  [SMALL_STATE(95)] = 1851,
  [SMALL_STATE(96)] = 1856,
  [SMALL_STATE(97)] = 1861,
  [SMALL_STATE(98)] = 1866,
  [SMALL_STATE(99)] = 1871,
  [SMALL_STATE(100)] = 1876,
  [SMALL_STATE(101)] = 1881,
  [SMALL_STATE(102)] = 1886,
  [SMALL_STATE(103)] = 1893,
  [SMALL_STATE(104)] = 1900,
  [SMALL_STATE(105)] = 1905,
  [SMALL_STATE(106)] = 1910,
  [SMALL_STATE(107)] = 1914,
  [SMALL_STATE(108)] = 1918,
  [SMALL_STATE(109)] = 1922,
  [SMALL_STATE(110)] = 1926,
  [SMALL_STATE(111)] = 1930,
  [SMALL_STATE(112)] = 1934,
  [SMALL_STATE(113)] = 1938,
  [SMALL_STATE(114)] = 1942,
  [SMALL_STATE(115)] = 1946,
  [SMALL_STATE(116)] = 1950,
  [SMALL_STATE(117)] = 1954,
  [SMALL_STATE(118)] = 1958,
  [SMALL_STATE(119)] = 1962,
  [SMALL_STATE(120)] = 1966,
  [SMALL_STATE(121)] = 1970,
  [SMALL_STATE(122)] = 1974,
  [SMALL_STATE(123)] = 1978,
  [SMALL_STATE(124)] = 1982,
  [SMALL_STATE(125)] = 1986,
  [SMALL_STATE(126)] = 1990,
  [SMALL_STATE(127)] = 1994,
  [SMALL_STATE(128)] = 1998,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(120),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(126),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(101),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(104),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [69] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [79] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [87] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [107] = {.entry = {.count = 1, .reusable = false}}, SHIFT(95),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [115] = {.entry = {.count = 1, .reusable = false}}, SHIFT(105),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [119] = {.entry = {.count = 1, .reusable = false}}, SHIFT(123),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [123] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [129] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(23),
  [132] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(120),
  [135] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(126),
  [138] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(36),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__jinja_comment, 2),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__jinja_comment, 2),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 1),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text, 1),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_text, 1),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 3),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 3),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 1),
  [177] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 1),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, .production_id = 2),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jinja_expression, 2),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jinja_expression, 2),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple, 2),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple, 5),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple, 3),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dict, 3),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dict, 2),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 5),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn_call, 2, .production_id = 1),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bool, 1),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 2),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 5),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 3),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 4),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dict, 4),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dict, 5),
  [217] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2), SHIFT_REPEAT(22),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple, 4),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 4),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [240] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_dict_repeat1, 2), SHIFT_REPEAT(33),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_dict_repeat1, 2),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [279] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2), SHIFT_REPEAT(19),
  [282] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [288] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_kwarg, 3, .production_id = 3),
  [290] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pair, 3, .production_id = 3),
  [292] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [298] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_single_quote, 1),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [312] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_double_quote, 1),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [316] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_jinja2(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
